// Figure profiles. Vector order: econ, power, culture, nation, faith, belong, war, justice, ecology, method, pop.
// pop comes from the Global Populism Database where it covers the person, otherwise from V-Party's party
// populism index (v = 150 x index - 60); for everyone else it is null and skipped in matching.
// Scores place each person on the present-day spectrum (the one the test-taker answers on), from what
// they did and said publicly, not relative to their own era. A 19th-century president who enslaved people
// scores high on Exclusion because that is where the position sits today.
// Presidents and heads of government with party data blend the record with V-Party codes for their party
// (economy, immigration, religion, LGBT rights) and with Herre (2023) on economics; see each profile's flag.
// null = no usable public record on that axis; the axis is skipped for that person.
// conf: how much documented political record the estimate rests on (high / medium / low).
// src: the published sources each profile was checked against. flag: a caveat from V-Dem regime codings.
// Economy scores were checked against Herre (2023); party positions against V-Party where the leader had a party.
const FIGURE_CATEGORIES = {
  president: 'US presidents',
  leader: 'Heads of government',
  activist: 'Politicians & activists',
  militant: 'Militant & terrorist leaders',
  ruler: 'Dictators & heads of state',
  public: 'Celebrities & notorious figures'
};

// Divisive figures: dictators, militant and terrorist leaders, and notorious public figures. Results show the
// closest of everyone and, separately, the closest divisive figure.
const DIVISIVE = ['militant', 'ruler', 'public'];

const FIGURES = [
  // ---- US presidents, in order ----
  { n: 'George Washington', c: 'president', y: '1789–1797', l: 'Federalist-leaning nonpartisan', conf: 'medium',
    v: [40, 20, 70, 60, 30, 60, 10, 60, 30, 20, null],
    note: 'Backed Hamilton\'s national bank and assumption of debts, proclaimed neutrality in Europe\'s wars, crushed the Whiskey Rebellion. Enslaved over 100 people; freed them in his will. Led an armed revolution before taking office.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'John Adams', c: 'president', y: '1797–1801', l: 'Federalist', conf: 'medium',
    v: [30, 55, 70, 50, 45, 40, 20, 60, null, 0, null],
    note: 'Signed the Alien and Sedition Acts, used to prosecute critical newspaper editors. Fought an undeclared naval war with France but avoided full war. Never owned enslaved people.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Thomas Jefferson', c: 'president', y: '1801–1809', l: 'Democratic-Republican', conf: 'high',
    v: [30, -60, 40, 30, -60, 65, 0, 40, 0, 50, null],
    note: 'Author of the Virginia Statute for Religious Freedom; championed small government and yeoman farmers. Enslaved over 600 people over his life and wrote of Black inferiority. "The tree of liberty must be refreshed from time to time with the blood of patriots."',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'James Madison', c: 'president', y: '1809–1817', l: 'Democratic-Republican', conf: 'medium',
    v: [30, -20, 50, 40, -50, 55, 30, 40, null, 10, null],
    note: 'Architect of the Constitution and Bill of Rights, strict on church-state separation. Led the country into the War of 1812. Enslaver.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'James Monroe', c: 'president', y: '1817–1825', l: 'Democratic-Republican', conf: 'medium',
    v: [30, 10, 55, 60, 0, 55, 30, null, null, 0, null],
    note: 'Monroe Doctrine: the Americas closed to European colonization. Enslaver; backed colonization of freed Black Americans in Liberia.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'John Quincy Adams', c: 'president', y: '1825–1829', l: 'National Republican', conf: 'medium',
    v: [10, 30, 40, 40, 30, 10, 0, null, 50, -60, null],
    note: 'Pushed federal roads, canals and a national university. Later in Congress the leading opponent of the gag rule on slavery petitions; argued the Amistad case.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Andrew Jackson', c: 'president', y: '1829–1837', l: 'Jacksonian Democrat', conf: 'high',
    v: [40, 50, 60, 80, 10, 90, 70, 70, 40, 30, null],
    note: 'Killed the Second Bank, signed the Indian Removal Act leading to the Trail of Tears, ignored the Supreme Court in Worcester v. Georgia. Enslaver.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Martin Van Buren', c: 'president', y: '1837–1841', l: 'Jacksonian Democrat; later Free Soil', conf: 'medium',
    v: [50, 0, 50, 40, 0, 70, 10, null, null, -20, null],
    note: 'Carried out Cherokee removal and refused to annex Texas. Ran in 1848 on the anti-slavery-expansion Free Soil ticket.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'William Henry Harrison', c: 'president', y: '1841', l: 'Whig', conf: 'low',
    v: [30, 0, 60, 50, 10, 70, 60, null, null, 0, null],
    note: 'Died a month into office. Career defined by wars against Native nations (Tippecanoe) and treaties taking their land.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'John Tyler', c: 'president', y: '1841–1845', l: 'States\'-rights Democrat', conf: 'medium',
    v: [50, -20, 70, 60, 10, 90, 40, null, null, 40, null],
    note: 'Vetoed the Whig bank bills, annexed Texas as a slave state. Later elected to the Confederate Congress.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'James K. Polk', c: 'president', y: '1845–1849', l: 'Jacksonian Democrat', conf: 'high',
    v: [40, 20, 60, 90, 10, 85, 85, null, null, 0, null],
    note: 'Manifest Destiny: provoked and won the Mexican-American War, taking about half of Mexico. Lowered tariffs. Enslaver.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Zachary Taylor', c: 'president', y: '1849–1850', l: 'Whig', conf: 'low',
    v: [20, 10, 60, 50, 0, 70, 50, null, null, -20, null],
    note: 'Career general and enslaver who nonetheless threatened to hang secessionists and opposed slavery\'s spread into new territories.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Millard Fillmore', c: 'president', y: '1850–1853', l: 'Whig; later Know-Nothing', conf: 'medium',
    v: [30, 20, 60, 60, 30, 75, 10, null, null, -30, null],
    note: 'Signed the Fugitive Slave Act. Ran in 1856 for the anti-Catholic, anti-immigrant American (Know-Nothing) Party.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Franklin Pierce', c: 'president', y: '1853–1857', l: 'Northern pro-slavery Democrat', conf: 'medium',
    v: [40, 10, 60, 70, 0, 80, 40, null, null, 0, null],
    note: 'Signed the Kansas-Nebraska Act; his envoys drafted the Ostend Manifesto on acquiring Cuba.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'James Buchanan', c: 'president', y: '1857–1861', l: 'Pro-Southern Democrat', conf: 'medium',
    v: [40, 20, 60, 60, 10, 85, 20, null, null, -10, null],
    note: 'Pressed for the Dred Scott outcome and the pro-slavery Lecompton constitution; held that secession was illegal but that he could not stop it.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Abraham Lincoln', c: 'president', y: '1861–1865', l: 'Republican (Whig roots)', conf: 'high',
    v: [10, 50, 40, 60, 20, 10, 60, 40, 60, -30, null],
    note: 'Won the Civil War, issued the Emancipation Proclamation, pushed the 13th Amendment. Suspended habeas corpus. Backed tariffs, railroads and the Homestead Act. Held some racial views that would be disqualifying today.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Andrew Johnson', c: 'president', y: '1865–1869', l: 'War Democrat / Unionist', conf: 'high',
    v: [30, 0, 60, 50, 10, 90, 0, null, null, 0, null],
    note: 'Vetoed the Civil Rights Act of 1866 and the Freedmen\'s Bureau bill; pardoned Confederates en masse. Impeached, acquitted by one vote.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Ulysses S. Grant', c: 'president', y: '1869–1877', l: 'Republican', conf: 'high',
    v: [20, 40, 30, 50, 10, -10, 30, 50, 50, -40, null],
    note: 'Enforced Reconstruction, used federal troops and courts to break the first Ku Klux Klan. His administration also waged the later Plains wars.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Rutherford B. Hayes', c: 'president', y: '1877–1881', l: 'Republican', conf: 'medium',
    v: [30, 0, 50, 40, 30, 30, 10, null, null, -40, null],
    note: 'Withdrew federal troops from the South, ending Reconstruction. Used troops against the 1877 railroad strike.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'James A. Garfield', c: 'president', y: '1881', l: 'Republican', conf: 'low',
    v: [30, 0, 40, 40, 30, 0, null, null, null, -40, null],
    note: 'Assassinated months into office. Strong advocate of Black suffrage and education.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Chester A. Arthur', c: 'president', y: '1881–1885', l: 'Republican', conf: 'medium',
    v: [20, 0, 40, 40, 10, 40, null, null, null, -50, null],
    note: 'Signed the Pendleton civil-service reform and, after a first veto, the Chinese Exclusion Act.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Grover Cleveland', c: 'president', y: '1885–1889, 1893–1897', l: 'Bourbon Democrat', conf: 'high',
    v: [60, -20, 50, 40, 20, 40, -30, null, null, -50, null],
    note: 'Gold standard, low tariffs, record vetoes of spending bills. Sent troops to break the Pullman strike. Refused to annex Hawaii after the coup.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Benjamin Harrison', c: 'president', y: '1889–1893', l: 'Republican', conf: 'medium',
    v: [30, 20, 50, 70, 20, 30, 30, null, 40, -50, null],
    note: 'Signed the McKinley Tariff and Sherman Antitrust Act; backed federal protection of Black voting rights, which failed in the Senate.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'William McKinley', c: 'president', y: '1897–1901', l: 'Republican', conf: 'medium',
    v: [40, 20, 50, 60, 30, 30, 60, null, 60, -50, null],
    note: 'High tariffs and gold standard. Fought the Spanish-American War, annexed the Philippines, Puerto Rico, Guam and Hawaii.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Theodore Roosevelt', c: 'president', y: '1901–1909', l: 'Progressive Republican', conf: 'high',
    v: [-10, 50, 30, 60, 20, 30, 80, 50, -60, -40, null],
    note: 'Trust-busting, the Square Deal, 230 million acres of public lands protected. "Speak softly and carry a big stick." Ran in 1912 on a platform including social insurance.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'William Howard Taft', c: 'president', y: '1909–1913', l: 'Conservative Republican', conf: 'medium',
    v: [40, 10, 40, 50, 0, 20, 20, 40, 30, -80, null],
    note: 'Brought more antitrust suits than T. Roosevelt but was a legalist by temperament; later Chief Justice. Dollar diplomacy.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Woodrow Wilson', c: 'president', y: '1913–1921', l: 'Progressive Democrat', conf: 'high',
    v: [-10, 60, 40, -50, 30, 75, 40, 50, null, -30, null],
    note: 'Created the Federal Reserve and income tax, designed the League of Nations. Resegregated the federal civil service; Espionage and Sedition Acts jailed war critics.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Warren G. Harding', c: 'president', y: '1921–1923', l: 'Republican', conf: 'medium',
    v: [50, 0, 40, 60, 10, 30, -20, null, null, -40, null],
    note: '"Return to normalcy": tax cuts, tariff increases, the Washington Naval disarmament conference. Spoke for Black civil rights in Birmingham in 1921 and signed early immigration quotas.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Calvin Coolidge', c: 'president', y: '1923–1929', l: 'Conservative Republican', conf: 'high',
    v: [75, -10, 50, 50, 20, 50, -20, null, null, -70, null],
    note: 'Small government, tax cuts, vetoed farm subsidies. Signed the 1924 Immigration Act with its national-origins quotas.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Herbert Hoover', c: 'president', y: '1929–1933', l: 'Progressive-turned-conservative Republican', conf: 'high',
    v: [40, 0, 40, 50, 10, 40, -30, 40, 40, -60, null],
    note: 'Signed Smoot-Hawley tariffs; resisted direct federal relief during the Depression. Oversaw deportations of Mexicans and Mexican Americans.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Franklin D. Roosevelt', c: 'president', y: '1933–1945', l: 'New Deal liberal', conf: 'high',
    v: [-60, 50, 0, 10, 10, 50, 60, 40, -20, -30, null],
    note: 'New Deal, Social Security, Wagner Act, Civilian Conservation Corps. Led the US through WWII. Ordered internment of Japanese Americans; tried to pack the Supreme Court.',
    src: ['Historical record of the administration; no ideology dataset covers it'],
    flag: 'No dataset covers this presidency; every axis is scored from the historical record, placed on the present-day spectrum.' },
  { n: 'Harry S. Truman', c: 'president', y: '1945–1953', l: 'Fair Deal Democrat', conf: 'high',
    v: [-20, 30, 0, -40, 20, 0, 70, 40, 40, -60, null],
    note: 'Dropped the atomic bombs, founded NATO, fought in Korea, desegregated the armed forces. Proposed national health insurance.',
    src: ['Herre (2023), Global Leader Ideologies: coded centrist'],
    flag: 'Economy blends the record with Herre\'s party-based code; other axes are scored from the record.' },
  { n: 'Dwight D. Eisenhower', c: 'president', y: '1953–1961', l: 'Moderate Republican', conf: 'high',
    v: [30, 10, 30, -10, 40, 10, 30, 40, 40, -80, null],
    note: 'Kept New Deal programs, built the Interstate system, sent troops to Little Rock, warned of the military-industrial complex. Added "under God" to the Pledge. CIA coups in Iran and Guatemala.',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist'],
    flag: 'Economy blends the record with Herre\'s party-based code; other axes are scored from the record.' },
  { n: 'John F. Kennedy', c: 'president', y: '1961–1963', l: 'Cold War liberal', conf: 'high',
    v: [-10, 10, 0, -30, 10, -20, 60, null, null, -70, null],
    note: 'Bay of Pigs, Cuban Missile Crisis, escalation in Vietnam; proposed the Civil Rights Act and tax cuts.',
    src: ['Herre (2023), Global Leader Ideologies: coded centrist'],
    flag: 'Economy blends the record with Herre\'s party-based code; other axes are scored from the record.' },
  { n: 'Lyndon B. Johnson', c: 'president', y: '1963–1969', l: 'Great Society liberal', conf: 'high',
    v: [-30, 20, -20, -20, 20, -60, 75, 30, -20, -70, null],
    note: 'Civil Rights Act, Voting Rights Act, Medicare, Medicaid, the 1965 immigration reform. Massive escalation of the Vietnam War.',
    src: ['Herre (2023), Global Leader Ideologies: coded centrist'],
    flag: 'Economy blends the record with Herre\'s party-based code; other axes are scored from the record.' },
  { n: 'Richard Nixon', c: 'president', y: '1969–1974', l: 'Moderate-to-conservative Republican', conf: 'high',
    v: [25, 60, 30, 10, -21, -3, 60, 70, -40, 10, -15],
    note: 'Created the EPA, imposed wage-price controls, opened to China, launched the war on drugs, bombed Cambodia. Resigned over Watergate.',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Party (Lührmann et al. 2020), Republican Party 1972: economy 4.1 of 6 (0 = far left), immigration 2.3 of 4 (0 = strongly against), religious appeals 3.0 of 4 (0 = constant), LGBT equality 1.0 of 4 (0 = strongly against), populism index 0.30'],
    flag: 'Economy, immigration and religion (and LGBT rights from 1990) blend the record with V-Party codes for the president\'s party at election; the party is not the person.' },
  { n: 'Gerald Ford', c: 'president', y: '1974–1977', l: 'Moderate Republican', conf: 'medium',
    v: [39, 0, 0, -10, -16, -18, 10, null, null, -80, -15],
    note: 'Pardoned Nixon, signed the Helsinki Accords, supported the Equal Rights Amendment.',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Party (Lührmann et al. 2020), Republican Party 1976: economy 4.1 of 6 (0 = far left), immigration 2.3 of 4 (0 = strongly against), religious appeals 3.0 of 4 (0 = constant), LGBT equality 1.0 of 4 (0 = strongly against), populism index 0.30'],
    flag: 'Economy, immigration and religion (and LGBT rights from 1990) blend the record with V-Party codes for the president\'s party at election; the party is not the person.' },
  { n: 'Jimmy Carter', c: 'president', y: '1977–1981', l: 'Moderate Democrat', conf: 'high',
    v: [-12, -10, 10, -50, 5, -49, -40, -10, -70, -90, -15],
    note: 'Camp David Accords, human-rights foreign policy, solar panels on the White House, deregulated airlines and trucking. An evangelical Baptist.',
    src: ['Herre (2023), Global Leader Ideologies: coded centrist', 'V-Party (Lührmann et al. 2020), Democratic Party 1976: economy 2.2 of 6 (0 = far left), immigration 3.0 of 4 (0 = strongly against), religious appeals 2.6 of 4 (0 = constant), LGBT equality 2.2 of 4 (0 = strongly against), populism index 0.30'],
    flag: 'Economy, immigration and religion (and LGBT rights from 1990) blend the record with V-Party codes for the president\'s party at election; the party is not the person.' },
  { n: 'Ronald Reagan', c: 'president', y: '1981–1989', l: 'Fusionist conservative', conf: 'high',
    v: [58, 20, 60, 40, 5, 4, 70, 70, 40, -60, -20],
    note: 'Cut top tax rates from 70% to 28%, large defense buildup, war on drugs. Signed the 1986 amnesty for about 3 million undocumented immigrants.',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Party (Lührmann et al. 2020), Republican Party 1980–84: economy 4.5 of 6 (0 = far left), immigration 1.8 of 4 (0 = strongly against), religious appeals 2.6 of 4 (0 = constant), LGBT equality 1.4 of 4 (0 = strongly against), populism index 0.27'],
    flag: 'Economy, immigration and religion (and LGBT rights from 1990) blend the record with V-Party codes for the president\'s party at election; the party is not the person.' },
  { n: 'George H. W. Bush', c: 'president', y: '1989–1993', l: 'Establishment Republican', conf: 'high',
    v: [48, 10, 40, -30, 10, 4, 60, 60, 20, -80, -16],
    note: 'Gulf War coalition, Americans with Disabilities Act, Clean Air Act amendments, raised taxes despite "read my lips."',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Party (Lührmann et al. 2020), Republican Party 1988: economy 4.6 of 6 (0 = far left), immigration 1.6 of 4 (0 = strongly against), religious appeals 2.2 of 4 (0 = constant), LGBT equality 1.4 of 4 (0 = strongly against), populism index 0.30'],
    flag: 'Economy, immigration and religion (and LGBT rights from 1990) blend the record with V-Party codes for the president\'s party at election; the party is not the person.' },
  { n: 'Bill Clinton', c: 'president', y: '1993–2001', l: 'New Democrat / Third Way', conf: 'high',
    v: [3, 10, -26, -60, -17, -16, 40, 60, -10, -80, -19],
    note: 'NAFTA, welfare reform, the 1994 crime bill, balanced budgets, Defense of Marriage Act, Kosovo intervention.',
    src: ['Herre (2023), Global Leader Ideologies: coded centrist', 'V-Party (Lührmann et al. 2020), Democratic Party 1992–96: economy 2.6 of 6 (0 = far left), immigration 1.8 of 4 (0 = strongly against), religious appeals 2.7 of 4 (0 = constant), LGBT equality 2.6 of 4 (0 = strongly against), populism index 0.28'],
    flag: 'Economy, immigration and religion (and LGBT rights from 1990) blend the record with V-Party codes for the president\'s party at election; the party is not the person.' },
  { n: 'George W. Bush', c: 'president', y: '2001–2009', l: 'Neoconservative / compassionate conservative', conf: 'high',
    v: [49, 50, 38, 20, 23, 7, 90, 70, 40, -60, -35],
    note: 'Afghanistan and Iraq wars, the Patriot Act, warrantless surveillance, tax cuts, Medicare Part D, faith-based initiatives, pushed immigration reform.',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Party (Lührmann et al. 2020), Republican Party 2000–04: economy 4.4 of 6 (0 = far left), immigration 1.5 of 4 (0 = strongly against), religious appeals 2.1 of 4 (0 = constant), LGBT equality 1.6 of 4 (0 = strongly against), populism index 0.22', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.20 on a 0–2 scale (mean of 2 terms: 0.21, 0.19)'],
    flag: 'Economy, immigration and religion (and LGBT rights from 1990) blend the record with V-Party codes for the president\'s party at election; the party is not the person.' },
  { n: 'Barack Obama', c: 'president', y: '2009–2017', l: 'Liberal Democrat', conf: 'high',
    v: [-19, 20, -53, -60, -28, -26, 40, -20, -60, -80, -34],
    note: 'Affordable Care Act, Paris Agreement, Dodd-Frank, expanded drone strikes, Libya intervention, DACA. Came to back same-sex marriage in 2012.',
    src: ['Herre (2023), Global Leader Ideologies: coded centrist', 'V-Party (Lührmann et al. 2020), Democratic Party 2008–12: economy 2.2 of 6 (0 = far left), immigration 1.8 of 4 (0 = strongly against), religious appeals 2.7 of 4 (0 = constant), LGBT equality 3.1 of 4 (0 = strongly against), populism index 0.20', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.22 on a 0–2 scale (mean of 2 terms: 0.15, 0.29)'],
    flag: 'Economy, immigration and religion (and LGBT rights from 1990) blend the record with V-Party codes for the president\'s party at election; the party is not the person.' },
  { n: 'Donald Trump', c: 'president', y: '2017–2021, 2025–', l: 'Right-wing populist / national conservative', conf: 'high',
    v: [40, 60, 36, 90, 24, 57, 30, 80, 90, 40, 8],
    note: 'Broad tariffs, mass-deportation agenda, Paris withdrawal, tax cuts, appointed the justices who overturned Roe. Refused to accept the 2020 result; January 6.',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Party (Lührmann et al. 2020), Republican Party 2016–18: economy 4.5 of 6 (0 = far left), immigration 0.9 of 4 (0 = strongly against), religious appeals 1.6 of 4 (0 = constant), LGBT equality 1.6 of 4 (0 = strongly against), populism index 0.47', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.78 on a 0–2 scale (2017–2020 term)'],
    flag: 'Economy, immigration and religion (and LGBT rights from 1990) blend the record with V-Party codes for the president\'s party at election; the party is not the person.' },
  { n: 'Joe Biden', c: 'president', y: '2021–2025', l: 'Mainstream liberal Democrat', conf: 'high',
    v: [-33, 10, -67, -40, -13, -26, 10, -10, -60, -80, -12],
    note: 'Inflation Reduction Act climate spending, infrastructure law, pro-union stance, Afghanistan withdrawal, military aid to Ukraine and Israel. Practicing Catholic.',
    src: ['V-Party (Lührmann et al. 2020), Democratic Party 2018 (latest year coded): economy 2.2 of 6 (0 = far left), immigration 1.9 of 4 (0 = strongly against), religious appeals 2.7 of 4 (0 = constant), LGBT equality 3.7 of 4 (0 = strongly against), populism index 0.32'],
    flag: 'Economy, immigration and religion (and LGBT rights from 1990) blend the record with V-Party codes for the president\'s party at election; the party is not the person.' },
  // ---- Heads of government and world leaders ----
  { n: 'Winston Churchill', c: 'leader', y: 'UK, 1940–45, 1951–55', l: 'Conservative imperialist', conf: 'medium',
    v: [45, 40, 60, 60, 30, 60, 80, 60, null, -60, null],
    note: 'Led Britain through the Second World War; opposed Indian self-rule and defended the empire; accepted much of the postwar welfare state on returning in 1951.',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'Roberts, Churchill: Walking with Destiny (2018)'] },
  { n: 'Charles de Gaulle', c: 'leader', y: 'France, 1944–46, 1958–69', l: 'Gaullism', conf: 'medium',
    v: [30, 60, 60, 90, 40, 30, 40, 60, null, -20, null],
    note: 'Founded the Fifth Republic with a strong presidency, ended the Algerian war, withdrew France from NATO\'s integrated command, vetoed British entry to the EEC.',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'Jackson, A Certain Idea of France (2018)'] },
  { n: 'Konrad Adenauer', c: 'leader', y: 'West Germany, 1949–63', l: 'Christian democracy', conf: 'medium',
    v: [40, 30, 50, -40, 60, 10, 30, 40, null, -80, null],
    note: 'First chancellor of the Federal Republic: social market economy, Western integration and NATO membership, reconciliation with France.',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'Williams, Adenauer: The Father of the New Germany (2000)'] },
  { n: 'Tony Blair', c: 'leader', y: 'UK, 1997–2007', l: 'Third Way social democracy', conf: 'high',
    v: [-16, 40, -39, -60, -42, -33, 80, 50, -10, -80, -42],
    note: 'New Labour: minimum wage, Bank of England independence, devolution, the Good Friday Agreement, the Iraq War, tougher criminal justice ("tough on crime, tough on the causes of crime").',
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Party (Lührmann et al. 2020), Labour 1997–2005: economy 2.8 of 6 (0 = far left), immigration 2.7 of 4 (0 = strongly against), religious appeals 3.9 of 4 (0 = constant), LGBT equality 3.0 of 4 (0 = strongly against), populism index 0.34', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.11 on a 0–2 scale (mean of 2 terms: 0.10, 0.13)', 'Seldon, Blair (2004)'],
    flag: 'Economy, immigration, religion and LGBT rights blend the record with V-Party codes for the leader\'s party; the party is not the person.' },
  { n: 'Angela Merkel', c: 'leader', y: 'Germany, 2005–21', l: 'Christian democracy', conf: 'high',
    v: [31, 0, 3, -70, 3, -13, -10, 20, -40, -90, -48],
    note: 'Led through the euro crisis and the 2015 refugee intake; phased out nuclear power; allowed a free vote that legalized same-sex marriage in 2017 while voting against it herself.',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Party (Lührmann et al. 2020), CDU 2005–17: economy 3.7 of 6 (0 = far left), immigration 1.7 of 4 (0 = strongly against), religious appeals 2.3 of 4 (0 = constant), LGBT equality 1.9 of 4 (0 = strongly against), populism index 0.06', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.03 on a 0–2 scale (mean of 3 terms: 0.00, 0.05, 0.04)', 'Kornelius, Angela Merkel: The Chancellor and Her World (2013)'],
    flag: 'Economy, immigration, religion and LGBT rights blend the record with V-Party codes for the leader\'s party; the party is not the person.' },
  { n: 'Emmanuel Macron', c: 'leader', y: 'France, 2017–', l: 'Liberal centrism', conf: 'high',
    v: [25, 20, -32, -80, -68, -5, 20, 30, -20, -80, -39],
    note: 'Founded En Marche outside the old parties; labor-market and pension reforms; strongly pro-EU; tightened immigration law in 2023.',
    src: ['V-Party (Lührmann et al. 2020), La République En Marche 2017: economy 3.6 of 6 (0 = far left), immigration 1.8 of 4 (0 = strongly against), religious appeals 3.9 of 4 (0 = constant), LGBT equality 2.7 of 4 (0 = strongly against), populism index 0.35', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.15 on a 0–2 scale (2017–2022 term)'],
    flag: 'Economy, immigration, religion and LGBT rights blend the record with V-Party codes for the leader\'s party; the party is not the person.' },
  { n: 'Justin Trudeau', c: 'leader', y: 'Canada, 2015–25', l: 'Progressive liberalism', conf: 'high',
    v: [-39, 0, -75, -50, -67, -59, -20, -30, -40, -90, -42],
    note: 'Carbon pricing, cannabis legalization, high immigration targets, the Canada Child Benefit; invoked the Emergencies Act against the 2022 convoy protests.',
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Party (Lührmann et al. 2020), Liberal Party 2015–19: economy 1.9 of 6 (0 = far left), immigration 3.2 of 4 (0 = strongly against), religious appeals 3.9 of 4 (0 = constant), LGBT equality 3.6 of 4 (0 = strongly against), populism index 0.29', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.11 on a 0–2 scale (2016–2019 term)'],
    flag: 'Economy, immigration, religion and LGBT rights blend the record with V-Party codes for the leader\'s party; the party is not the person.' },
  { n: 'Jacinda Ardern', c: 'leader', y: 'New Zealand, 2017–23', l: 'Social democracy', conf: 'high',
    v: [-39, 20, -60, -40, -70, -35, -40, -30, -60, -90, 3],
    note: 'Banned military-style semi-automatic weapons after Christchurch, pursued strict COVID elimination, set child-poverty and zero-carbon targets.',
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Party (Lührmann et al. 2020), Labour 2017: economy 2.2 of 6 (0 = far left), immigration 2.4 of 4 (0 = strongly against), religious appeals 3.8 of 4 (0 = constant), LGBT equality 3.2 of 4 (0 = strongly against), populism index 0.42'],
    flag: 'Economy, immigration, religion and LGBT rights blend the record with V-Party codes for the leader\'s party; the party is not the person.' },
  { n: 'Lula da Silva', c: 'leader', y: 'Brazil, 2003–10, 2023–', l: 'Democratic socialism (Workers\' Party)', conf: 'high',
    v: [-51, 0, -46, 20, -44, -38, -40, -20, 0, -60, -31],
    note: 'Former union leader: Bolsa Família cash transfers, minimum-wage increases, a large public development bank; later convicted on corruption charges that were annulled in 2021.',
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Party (Lührmann et al. 2020), Workers\' Party 2002–06: economy 1.7 of 6 (0 = far left), immigration 2.9 of 4 (0 = strongly against), religious appeals 3.9 of 4 (0 = constant), LGBT equality 3.6 of 4 (0 = strongly against), populism index 0.68', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.25 on a 0–2 scale (2003–2010 term)'],
    flag: 'Economy, immigration, religion and LGBT rights blend the record with V-Party codes for the leader\'s party; the party is not the person.' },
  { n: 'Narendra Modi', c: 'leader', y: 'India, 2014–', l: 'Hindu nationalism', conf: 'medium',
    v: [40, 60, 60, 80, 80, 70, 50, 60, 60, -10, -9],
    note: 'BJP prime minister: demonetization, revoking Kashmir\'s special status, the Citizenship Amendment Act; critics and the V-Dem Institute describe democratic backsliding.',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.55 on a 0–2 scale (2014–2019 term)', 'Jaffrelot, Modi\'s India (2021)'] },
  { n: 'Viktor Orbán', c: 'leader', y: 'Hungary, 1998–2002, 2010–26', l: 'National conservatism', conf: 'high',
    v: [3, 60, 66, 90, 33, 65, 10, 60, 40, -30, 2],
    note: 'Self-described "illiberal democracy": a new constitution, control of courts and media, border fence and anti-immigration campaigns, pro-natalist family policy.',
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Party (Lührmann et al. 2020), Fidesz 2010–18: economy 4.2 of 6 (0 = far left), immigration 1.0 of 4 (0 = strongly against), religious appeals 1.9 of 4 (0 = constant), LGBT equality 1.0 of 4 (0 = strongly against), populism index 0.82', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.69 on a 0–2 scale (mean of 3 terms: 0.38, 0.88, 0.83)', 'Herre codes him leftist on economics, against V-Party\'s center-right coding of Fidesz; the economy score blends both'],
    flag: 'Economy, immigration, religion and LGBT rights blend the record with V-Party codes for the leader\'s party; the party is not the person.' },
  { n: 'Benjamin Netanyahu', c: 'leader', y: 'Israel, 1996–99, 2009–21, 2022–', l: 'Likud national conservatism', conf: 'high',
    v: [51, 50, 21, 80, 9, 41, 80, 60, 40, -30, -27],
    note: 'Market reforms as finance minister, hawkish on Iran and the Palestinians, the 2018 nation-state law, a judicial overhaul that drew mass protests, and the war in Gaza after October 7, 2023.',
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Party (Lührmann et al. 2020), Likud 2009–19: economy 4.2 of 6 (0 = far left), immigration 1.6 of 4 (0 = strongly against), religious appeals 2.6 of 4 (0 = constant), LGBT equality 1.9 of 4 (0 = strongly against), populism index 0.55', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.31 on a 0–2 scale (mean of 5 terms, rising from 0.19 to 0.71)'],
    flag: 'Economy, immigration, religion and LGBT rights blend the record with V-Party codes for the leader\'s party; the party is not the person.' },
  { n: 'Nelson Mandela', c: 'leader', y: 'South Africa, 1994–99', l: 'African nationalist social democracy', conf: 'high',
    v: [-40, -30, -39, 0, -14, -53, -30, -60, null, -30, 56],
    note: 'Co-founded the ANC\'s armed wing in 1961 after peaceful protest was banned; imprisoned 27 years; as president led reconciliation, the Truth and Reconciliation Commission and a liberal constitution.',
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Party (Lührmann et al. 2020), ANC 1994: economy 1.8 of 6 (0 = far left), immigration 2.3 of 4 (0 = strongly against), religious appeals 2.7 of 4 (0 = constant), LGBT equality 2.7 of 4 (0 = strongly against), populism index 0.77', 'Mandela, Long Walk to Freedom (1994)'],
    flag: 'Economy, immigration, religion and LGBT rights blend the record with V-Party codes for the leader\'s party; the party is not the person.' },
  { n: 'Volodymyr Zelensky', c: 'leader', y: 'Ukraine, 2019–', l: 'Centrist populism, wartime nationalism', conf: 'medium',
    v: [25, 30, -22, 40, -49, -28, 60, 30, null, -70, 74],
    note: 'Comedian elected on an anti-corruption platform; has led Ukraine\'s defense against Russia\'s 2022 invasion, under martial law and with elections postponed.',
    src: ['V-Party (Lührmann et al. 2020), Servant of the People 2019: economy 3.9 of 6 (0 = far left), immigration 2.7 of 4 (0 = strongly against), religious appeals 3.7 of 4 (0 = constant), LGBT equality 2.5 of 4 (0 = strongly against), populism index 0.90'],
    flag: 'Economy, immigration, religion and LGBT rights blend the record with V-Party codes for the leader\'s party; the party is not the person.' },
  { n: 'Mikhail Gorbachev', c: 'leader', y: 'USSR, 1985–91', l: 'Reform communism', conf: 'medium',
    v: [-50, 0, -10, -40, -60, -30, -60, null, null, -60, null],
    note: 'Glasnost and perestroika, withdrawal from Afghanistan, arms-control treaties; let Eastern Europe go in 1989 without force.',
    src: ['Taubman, Gorbachev: His Life and Times (2017)'] },
  { n: 'Javier Milei', c: 'leader', y: 'Argentina, 2023–', l: 'Anarcho-capitalist libertarianism', conf: 'medium',
    v: [95, -40, 60, 20, 30, 30, 10, 50, 80, -20, null],
    note: 'Economist elected on cutting the state "with a chainsaw": deep spending cuts, deregulation, devaluation; opposes abortion and calls climate change a socialist lie.',
    src: ['Milei\'s own speeches and program, 2023 campaign'] },
  // ---- Politicians and activists ----
  { n: 'Mahatma Gandhi', c: 'activist', y: 'Indian independence, 1915–1948', l: 'Gandhian nonviolence', conf: 'high',
    v: [-50, -70, 40, 60, 70, -60, -100, -60, -90, 20, null],
    note: 'Mass civil disobedience against British rule, village self-sufficiency, opposed industrialization. Defended Muslim-Hindu unity. Extra-legal but strictly nonviolent.' },
  { n: 'Martin Luther King Jr.', c: 'activist', y: 'Civil rights, 1955–1968', l: 'Christian democratic socialism', conf: 'high',
    v: [-60, -30, 0, -40, 60, -90, -90, -50, null, 0, null],
    note: 'Baptist minister who led nonviolent civil disobedience against segregation. Opposed the Vietnam War; launched the Poor People\'s Campaign for economic justice.' },
  { n: 'Malcolm X', c: 'activist', y: 'Nation of Islam and after, 1952–1965', l: 'Black nationalism', conf: 'medium',
    v: [-40, 10, 30, 50, 80, 40, 20, null, null, 60, null],
    note: 'Preached Black separatism and self-defense "by any means necessary" with the Nation of Islam; after Mecca in 1964 moved toward Sunni Islam and broader human-rights framing.' },
  { n: 'Bernie Sanders', c: 'activist', y: 'US Senator, 2007–', l: 'Democratic socialism', conf: 'high',
    v: [-80, -10, -50, -10, -30, -50, -50, -50, -80, -60, null],
    note: 'Medicare for All, free public college, Green New Deal. Opposed the Iraq War and, early on, some free trade deals.' },
  { n: 'Ron Paul', c: 'activist', y: 'US Representative, 1976–2013', l: 'Paleolibertarianism', conf: 'high',
    v: [90, -80, 40, 50, 40, 10, -90, -30, 40, -50, null],
    note: 'Abolish the Fed and the income tax, end the drug war, bring troops home. Personally pro-life; opposed birthright citizenship for children of undocumented immigrants.' },

  // ---- Militant and terrorist leaders ----
  { n: 'Osama bin Laden', c: 'militant', y: 'al-Qaeda, 1988–2011', l: 'Salafi-jihadism', conf: 'high',
    v: [-10, 90, 100, -20, 100, 85, 95, 100, -30, 100, null],
    src: ['Lawrence, ed., Messages to the World: The Statements of Osama bin Laden (2005)', 'Wiktorowicz (2006), "Anatomy of the Salafi Movement," Studies in Conflict & Terrorism', 'Hegghammer, Jihad in Saudi Arabia (2010)'],
    note: 'Founded al-Qaeda; ordered the 9/11 attacks. Called for a transnational caliphate under strict sharia. His statements attacked usury and, in 2010, blamed the West for climate change.' },
  { n: 'Ayman al-Zawahiri', c: 'militant', y: 'al-Qaeda, 2011–2022', l: 'Salafi-jihadism', conf: 'high',
    v: [-10, 90, 100, -20, 100, 85, 95, 100, null, 100, null],
    src: ['al-Zawahiri, Knights Under the Prophet\'s Banner (2001)', 'Letter from al-Zawahiri to al-Zarqawi (2005), released by the US ODNI', 'Wiktorowicz (2006)'],
    note: 'Egyptian Islamic Jihad founder, al-Qaeda\'s chief ideologue and later leader. Wrote "Knights Under the Prophet\'s Banner."' },
  { n: 'Abu Bakr al-Baghdadi', c: 'militant', y: 'ISIS, 2010–2019', l: 'Salafi-jihadism (takfiri)', conf: 'high',
    v: [null, 100, 100, -30, 100, 100, 100, 100, null, 100, null],
    src: ['Bunzel (2015), From Paper State to Caliphate, Brookings', 'UN Commission of Inquiry on Syria (2016), "They Came to Destroy": ISIS Crimes Against the Yazidis'],
    note: 'Declared the ISIS caliphate in 2014. Genocide of Yazidis, mass executions of Shia and of Sunnis deemed apostates, sexual slavery.' },
  { n: 'Abu Musab al-Zarqawi', c: 'militant', y: 'al-Qaeda in Iraq, 2004–2006', l: 'Salafi-jihadism (takfiri)', conf: 'high',
    v: [null, 95, 100, -20, 100, 100, 100, 100, null, 100, null],
    src: ['Bunzel (2015), From Paper State to Caliphate, Brookings', 'Letter from al-Zawahiri to al-Zarqawi (2005) criticizing attacks on Shia civilians'],
    note: 'Led al-Qaeda in Iraq; deliberately targeted Shia civilians to start a sectarian war. The organization became ISIS.' },
  { n: 'Mullah Omar', c: 'militant', y: 'Taliban, 1994–2013', l: 'Deobandi Islamism', conf: 'medium',
    v: [null, 95, 100, 40, 100, 80, 60, 100, null, 90, null],
    src: ['Rashid, Taliban (2000)', 'Strick van Linschoten & Kuehn, An Enemy We Created (2012)'],
    note: 'Founded the Taliban; as emir ran Afghanistan under strict sharia, banned girls\' schooling, destroyed the Bamiyan Buddhas, sheltered bin Laden. Goals were mostly confined to Afghanistan.' },
  { n: 'Abubakar Shekau', c: 'militant', y: 'Boko Haram, 2009–2021', l: 'Salafi-jihadism', conf: 'medium',
    v: [null, 100, 100, -10, 100, 100, 100, 100, null, 100, null],
    src: ['Thurston, Boko Haram: The History of an African Jihadist Movement (2017)'],
    note: 'Led Boko Haram, whose name rejects Western education; the Chibok kidnapping of 276 schoolgirls, mass killings of Muslims and Christians.' },
  { n: 'Hassan Nasrallah', c: 'militant', y: 'Hezbollah, 1992–2024', l: 'Khomeinism', conf: 'high',
    v: [-20, 70, 80, 40, 95, 50, 80, 70, null, 70, null],
    src: ['Norton, Hezbollah: A Short History (2007)', 'Hezbollah, Open Letter (1985) and Political Document (2009)'],
    note: 'Led Hezbollah\'s militia and its political party, which sat in Lebanon\'s parliament and cabinets. Loyal to Iran\'s Supreme Leader; ran a large social-services network.' },
  { n: 'Yahya Sinwar', c: 'militant', y: 'Hamas, 2017–2024', l: 'Islamist nationalism', conf: 'high',
    v: [null, 80, 85, 80, 95, 85, 95, 90, null, 100, null],
    src: ['Hamas Charter (1988) and Document of General Principles and Policies (2017)', 'Hroub, Hamas: Political Thought and Practice (2000)'],
    note: 'Hamas leader in Gaza and planner of the October 7, 2023 attack. Known earlier for executing suspected collaborators. Hamas\'s 2017 policy document accepted a state on 1967 lines as an interim step and dropped the 1988 charter\'s antisemitic language; his conduct is scored, not the document.' },
  { n: 'Abimael Guzmán', c: 'militant', y: 'Shining Path, 1969–1992', l: 'Maoism ("Gonzalo Thought")', conf: 'high',
    v: [-100, 100, -20, 0, -100, 20, 90, 90, null, 100, null],
    src: ['Peru Truth and Reconciliation Commission, Final Report (2003)', 'Gorriti, The Shining Path: A History of the Millenarian War in Peru (1999)'],
    note: 'Philosophy professor who launched a people\'s war in Peru; massacres of peasants who resisted. The Truth Commission attributed about half of some 69,000 deaths in the conflict to the Shining Path.' },
  { n: 'Ulrike Meinhof', c: 'militant', y: 'Red Army Faction, 1970–1976', l: 'Anti-imperialist Marxism', conf: 'medium',
    v: [-90, 0, -70, -80, -80, -60, -50, null, null, 95, null],
    src: ['RAF, The Urban Guerrilla Concept (1971)', 'Aust, The Baader-Meinhof Complex (2008 ed.)', 'Rapoport (2004), "The Four Waves of Modern Terrorism": new-left wave'],
    note: 'Left-wing journalist turned co-founder of the Baader-Meinhof Group: bombings and kidnappings against West German institutions and US bases, framed as resistance to the Vietnam War.' },
  { n: 'George Habash', c: 'militant', y: 'PFLP, 1967–2000', l: 'Revolutionary Marxist nationalism', conf: 'medium',
    v: [-85, 60, -30, 80, -70, 20, 80, null, null, 100, null],
    src: ['Mapping Militant Organizations (Stanford/CISAC): Popular Front for the Liberation of Palestine', 'Rapoport (2004), new-left wave'],
    note: 'Christian-born founder of the Popular Front for the Liberation of Palestine; pioneered airliner hijackings in 1968–70.' },
  { n: 'Abdullah Öcalan', c: 'militant', y: 'PKK, 1978–', l: 'Democratic confederalism (earlier Marxism-Leninism)', conf: 'medium',
    v: [-70, -40, -70, 30, -50, -40, 40, -30, -70, 70, null],
    src: ['Öcalan, Democratic Confederalism (2011)', 'Mapping Militant Organizations (Stanford/CISAC): Kurdistan Workers\' Party'],
    note: 'Founded the PKK as a Marxist-Leninist separatist guerrilla army. Imprisoned since 1999, he rewrote its aims around stateless local democracy, women\'s liberation and ecology. Called for the PKK to disarm in 2025. Scored on his later thought.' },
  { n: 'Velupillai Prabhakaran', c: 'militant', y: 'LTTE, 1976–2009', l: 'Tamil militant separatism', conf: 'medium',
    v: [-40, 90, -10, 100, -30, 70, 95, 90, null, 100, null],
    src: ['Mapping Militant Organizations (Stanford/CISAC): Liberation Tigers of Tamil Eelam', 'Pape, Dying to Win (2005)'],
    note: 'Built the Tamil Tigers into a conventional army with a navy; pioneered suicide bombings, assassinated Rajiv Gandhi, expelled Muslims from the north.' },
  { n: 'Shoko Asahara', c: 'militant', y: 'Aum Shinrikyo, 1987–1995', l: 'Apocalyptic religious cult', conf: 'medium',
    v: [null, 100, null, -40, 100, 60, 90, null, null, 100, null],
    src: ['Lifton, Destroying the World to Save It (1999)', 'Reader, Religious Violence in Contemporary Japan (2000)'],
    note: 'Guru who blended Buddhist, Hindu and Christian apocalypticism; ordered the 1995 sarin attack on the Tokyo subway. Ran in the 1990 Japanese election before turning to violence.' },
  { n: 'Ted Kaczynski', c: 'militant', y: 'Unabomber, 1978–1995', l: 'Anti-technology anarcho-primitivism', conf: 'high',
    v: [-20, -60, 30, null, -30, null, null, null, -100, 100, null],
    src: ['Kaczynski, Industrial Society and Its Future (1995)'],
    note: 'His manifesto, "Industrial Society and Its Future," calls for revolution against the industrial-technological system and spends long sections attacking leftism.' },
  { n: 'Timothy McVeigh', c: 'militant', y: 'Oklahoma City bombing, 1995', l: 'Anti-government militia movement', conf: 'medium',
    v: [50, -90, 30, 50, -10, 40, -60, null, null, 100, null],
    src: ['Michel & Herbeck, American Terrorist (2001)', 'Belew, Bring the War Home (2018)'],
    note: 'Gulf War veteran radicalized by Ruby Ridge and Waco; bombed a federal building, killing 168. Gun-rights absolutist influenced by "The Turner Diaries."' },
  { n: 'Anders Breivik', c: 'militant', y: 'Norway attacks, 2011', l: 'Counter-jihad ethnonationalism', conf: 'high',
    v: [30, 60, 90, 90, 40, 100, 80, 80, null, 100, null],
    src: ['Breivik, 2083: A European Declaration of Independence (2011)', 'Bangstad, Anders Breivik and the Rise of Islamophobia (2014)'],
    note: 'Murdered 77 people, mostly teenagers at a Labour Party youth camp. His manifesto attacks "cultural Marxism," Islam and multiculturalism and calls for cultural Christianity.' },
  { n: 'Joseph Kony', c: 'militant', y: 'Lord\'s Resistance Army, 1987–', l: 'Millenarian Christian militancy', conf: 'low',
    v: [null, 100, null, null, 60, null, 100, 100, null, 100, null],
    src: ['Allen & Vlassenroot, eds., The Lord\'s Resistance Army: Myth and Reality (2010)'],
    note: 'Claims to channel spirits and to fight for rule by the Ten Commandments. Abducted tens of thousands of children as soldiers and sex slaves. Allen & Vlassenroot argue the religious framing is overstated and that Acholi political grievances drove the movement, so Religion is scored lower than the rhetoric suggests.' },

  // ---- Dictators and heads of state ----
  { n: 'Vladimir Lenin', c: 'ruler', y: 'Soviet Russia, 1917–1924', l: 'Marxism-Leninism', conf: 'high',
    v: [-95, 85, -50, -80, -100, -30, 60, 80, 60, 100, null],
    src: ['Lenin, The State and Revolution (1917)', 'Service, Lenin: A Biography (2000)'],
    note: 'Led the October Revolution; founded the one-party state and the Cheka. Legalized abortion and divorce early on. Expected world revolution.' },
  { n: 'Joseph Stalin', c: 'ruler', y: 'USSR, 1924–1953', l: 'Marxism-Leninism (Stalinism)', conf: 'high',
    v: [-100, 100, 30, 60, -100, 60, 80, 100, 90, 90, null],
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'Kotkin, Stalin, vols. 1–2 (2014, 2017)', 'Timasheff, The Great Retreat (1946)'],
    note: 'Forced collectivization, the Great Terror, the Gulag, deportation of whole nationalities. Reversed early Soviet social liberalism; "socialism in one country."' },
  { n: 'Mao Zedong', c: 'ruler', y: 'PRC, 1949–1976', l: 'Maoism', conf: 'high',
    v: [-100, 100, -40, 40, -100, 30, 70, 90, 90, 100, null],
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'MacFarquhar & Schoenhals, Mao\'s Last Revolution (2006)', 'Dikötter, Mao\'s Great Famine (2010)'],
    note: 'Great Leap Forward famine, the Cultural Revolution against "the Four Olds." "Political power grows out of the barrel of a gun."' },
  { n: 'Pol Pot', c: 'ruler', y: 'Khmer Rouge, 1975–1979', l: 'Agrarian Maoism', conf: 'high',
    v: [-100, 100, -20, 100, -100, 90, 80, 100, -60, 100, null],
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'Kiernan, The Pol Pot Regime (1996)'],
    note: 'Emptied the cities, abolished money and religion, killed roughly a quarter of Cambodia\'s population. Targeted Vietnamese, Cham and Chinese minorities.' },
  { n: 'Adolf Hitler', c: 'ruler', y: 'Germany, 1933–1945', l: 'National Socialism', conf: 'high',
    v: [0, 100, 70, 100, 10, 100, 100, 100, 30, 90, null],
    src: ['Kershaw, Hitler, 2 vols. (1998, 2000)', 'Tooze, The Wages of Destruction (2006)', 'Buchheim & Scherner (2006), "The Role of Private Property in the Nazi Economy," Journal of Economic History', 'V-Dem v15, regime legitimation indicators (v2exl_legit*)'],
    flag: 'V-Dem codes this regime as legitimized heavily through the leader\'s person; positions reflect one ruler more than a party doctrine.',
    note: 'Totalitarian racial state, the Holocaust, wars of conquest. Private property kept under heavy state direction.' },
  { n: 'Benito Mussolini', c: 'ruler', y: 'Italy, 1922–1943', l: 'Fascism', conf: 'high',
    v: [10, 95, 60, 100, 20, 70, 95, 90, 60, 80, null],
    src: ['Paxton, The Anatomy of Fascism (2004)', 'Griffin, The Nature of Fascism (1991)', 'V-Dem v15, regime legitimation indicators (v2exl_legit*)'],
    flag: 'V-Dem codes this regime as legitimized heavily through the leader\'s person; positions reflect one ruler more than a party doctrine.',
    note: 'Coined "fascism," took power after the March on Rome, built the corporatist one-party state, invaded Ethiopia. Racial laws from 1938.' },
  { n: 'Francisco Franco', c: 'ruler', y: 'Spain, 1939–1975', l: 'National Catholicism', conf: 'high',
    v: [20, 90, 90, 90, 90, 60, 60, 95, null, 80, null],
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'Preston, Franco (1993)', 'V-Dem v15, regime legitimation indicators (v2exl_legit*): nationalist, conservative and religious legitimation'],
    note: 'Won the Civil War after a military coup; Catholic Church restored as state religion, regional languages suppressed. Market liberalization from 1959.' },
  { n: 'Augusto Pinochet', c: 'ruler', y: 'Chile, 1973–1990', l: 'Authoritarian free-market conservatism', conf: 'high',
    v: [80, 90, 70, 70, 40, 30, 60, 95, null, 80, null],
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'Rettig (1991) and Valech (2004) commission reports', 'V-Dem v15, regime legitimation indicators (v2exl_legit*): conservative legitimation'],
    note: 'Seized power in a coup; the "Chicago Boys" privatization program; thousands killed or disappeared. Stepped down after losing the 1988 plebiscite.' },
  { n: 'Fidel Castro', c: 'ruler', y: 'Cuba, 1959–2008', l: 'Marxism-Leninism', conf: 'high',
    v: [-90, 90, -10, 50, -70, -10, 60, 80, 40, 100, null],
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Dem v15, regime legitimation indicators (v2exl_legit*)'],
    flag: 'V-Dem codes this regime as legitimized heavily through the leader\'s person; positions reflect one ruler more than a party doctrine.',
    note: 'Took power by guerrilla war; nationalized the economy, one-party rule, sent troops to Angola. Persecuted gay men in the UMAP camps, later apologized.' },
  { n: 'Che Guevara', c: 'ruler', y: 'Cuba, 1959–1965', l: 'Guevarism (guerrilla Marxism)', conf: 'high',
    v: [-95, 80, -30, -60, -80, -10, 90, 90, null, 100, null],
    src: ['Anderson, Che Guevara: A Revolutionary Life (1997)', 'Guevara, Guerrilla Warfare (1960)'],
    note: 'Argentine revolutionary who oversaw executions at La Cabaña and pushed rapid nationalization. Called for "two, three, many Vietnams." Killed in Bolivia trying to export the revolution.' },
  { n: 'Ruhollah Khomeini', c: 'ruler', y: 'Iran, 1979–1989', l: 'Khomeinism', conf: 'high',
    v: [10, 90, 95, 60, 100, 70, 70, 95, null, 90, null],
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'Abrahamian, Khomeinism (1993)', 'V-Dem v15, regime legitimation indicators (v2exl_legit*): religious legitimation'],
    note: 'Led the Islamic Revolution, created rule of the jurist, the fatwa against Salman Rushdie, mass executions of prisoners in 1988. Herre codes him rightist on economics despite the 1980s nationalizations, so Economy is slightly right of center.' },
  { n: 'Kim Jong Un', c: 'ruler', y: 'North Korea, 2011–', l: 'Juche', conf: 'high',
    v: [-80, 100, 50, 100, -60, 80, 90, 100, 70, null, null],
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Dem v15, regime legitimation indicators (v2exl_legit*)'],
    flag: 'V-Dem codes this regime as legitimized heavily through the leader\'s person; positions reflect one ruler more than a party doctrine.',
    note: 'Third hereditary leader; nuclear and missile program, executions of his uncle and others, total control of information.' },
  { n: 'Vladimir Putin', c: 'ruler', y: 'Russia, 1999–', l: 'Authoritarian national conservatism', conf: 'high',
    v: [15, 85, 70, 90, 35, 40, 85, 80, 80, 20, -30],
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Party (Lührmann et al. 2020): United Russia, economy coded center (3.0 of 6), religious appeals moderate', 'V-Dem v15, regime legitimation indicators (v2exl_legit*): nationalist and conservative legitimation', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.27 on a 0–2 scale (mean of 4 terms 2000–2018: 0.05, 0.03, 0.50, 0.50)'],
    note: 'Invaded Ukraine in 2014 and 2022, "gay propaganda" laws, alliance with the Orthodox Church, oil-and-gas state economy, jailed and killed opponents.' },
  { n: 'Xi Jinping', c: 'ruler', y: 'China, 2012–', l: 'Marxism-Leninism with Chinese characteristics', conf: 'high',
    v: [-40, 95, 30, 70, -80, 50, 50, 80, 30, -30, null],
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Dem v15, regime legitimation indicators (v2exl_legit*): socialist legitimation'],
    note: 'Ended term limits, mass internment of Uyghurs, "common prosperity," tightened control of private firms. Promotes "ecological civilization" while expanding coal.' },
  { n: 'Maximilien Robespierre', c: 'ruler', y: 'France, 1793–1794', l: 'Jacobinism', conf: 'medium',
    v: [-20, 90, -60, 60, -20, 0, 60, 100, null, 100, null],
    src: ['McPhee, Robespierre: A Revolutionary Life (2012)', 'Furet, Interpreting the French Revolution (1978)'],
    note: 'Leading figure of the Committee of Public Safety during the Terror. Argued against slavery and for universal male suffrage; backed price controls. Replaced Catholic worship with the deist Cult of the Supreme Being.' },
  { n: 'Saddam Hussein', c: 'ruler', y: 'Iraq, 1979–2003', l: 'Ba\'athism', conf: 'high',
    v: [-40, 100, 30, 90, 20, 90, 95, 100, 70, 90, null],
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Party (Lührmann et al. 2020): Ba\'ath Party, economy left (1.6–2.0 of 6), religious appeals rising in the 1990s', 'Helfont, Compulsion in Religion (2018)'],
    note: 'Secular pan-Arab socialist one-party state, later an Islamic "Faith Campaign." Invaded Iran and Kuwait; the Anfal campaign and the Halabja gas attack against Kurds.' },
  { n: 'Muammar Gaddafi', c: 'ruler', y: 'Libya, 1969–2011', l: 'Third International Theory', conf: 'high',
    v: [-70, 95, 50, 60, 40, 40, 70, 95, 60, 90, null],
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'Vandewalle, A History of Modern Libya (2006)', 'V-Dem v15, regime legitimation indicators (v2exl_legit*): nationalist and socialist legitimation'],
    flag: 'V-Dem codes this regime as legitimized heavily through the leader\'s person; positions reflect one ruler more than a party doctrine.',
    note: 'Took power in a coup; the Green Book\'s "Islamic socialism" and nominal rule by people\'s committees. Sponsored the Lockerbie bombing and foreign militant groups.' },
  { n: 'Idi Amin', c: 'ruler', y: 'Uganda, 1971–1979', l: 'Military dictatorship', conf: 'medium',
    v: [null, 100, null, 90, 50, 100, 80, 100, null, 90, null],
    src: ['Herre (2023), Global Leader Ideologies: coded non-ideological', 'V-Dem v15, regime legitimation indicators (v2exl_legit*)'],
    flag: 'V-Dem codes this regime as barely legitimized by any ideology; the scores describe what was done, not a coherent program.',
    note: 'Seized power in a coup, expelled Uganda\'s roughly 80,000 Asians in 1972, killed an estimated 100,000 to 500,000 people. Invaded Tanzania, which ended his rule.' },
  { n: 'Robert Mugabe', c: 'ruler', y: 'Zimbabwe, 1980–2017', l: 'African nationalist socialism', conf: 'high',
    v: [-50, 90, 80, 90, 40, 80, 40, 80, null, 80, null],
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Party (Lührmann et al. 2020): ZANU-PF, economy left, strongly anti-LGBT, frequent encouragement of violence', 'CCJP & Legal Resources Foundation, Breaking the Silence (1997)'],
    flag: 'V-Dem codes this regime as legitimized heavily through the leader\'s person; positions reflect one ruler more than a party doctrine.',
    note: 'Guerrilla leader turned president. Gukurahundi massacres in Matabeleland, seizure of white-owned farms, hyperinflation. Called gay people "worse than dogs and pigs."' },
  { n: 'Hugo Chávez', c: 'ruler', y: 'Venezuela, 1999–2013', l: 'Bolivarian socialism', conf: 'high',
    v: [-80, 80, 0, 70, 20, -20, 30, 30, 60, 60, 84],
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Party (Lührmann et al. 2020): MVR/PSUV, economy far left, maximal populism, low commitment to pluralism, frequent encouragement of violence', 'Hawkins, Venezuela\'s Chavismo and Populism in Comparative Perspective (2010)', 'Global Populism Database v2.1 (Hawkins et al.): populism 1.78 on a 0–2 scale (mean of 3 terms 1999–2013: 1.92, 1.75, 1.67)'],
    flag: 'V-Dem codes this regime as legitimized heavily through the leader\'s person; positions reflect one ruler more than a party doctrine.',
    note: 'Led a failed coup in 1992, then won elections. Nationalized oil, steel and utilities, funded social programs with oil revenue, packed the courts, closed RCTV.' },
  { n: 'Bashar al-Assad', c: 'ruler', y: 'Syria, 2000–2024', l: 'Ba\'athism', conf: 'high',
    v: [-30, 100, 20, 80, -60, 50, 60, 100, null, null, null],
    src: ['Herre (2023), Global Leader Ideologies: coded leftist', 'V-Dem v15, regime legitimation indicators (v2exl_legit*): nationalist legitimation'],
    note: 'Inherited power from his father. Met the 2011 uprising with barrel bombs, chemical weapons and mass torture in prisons. Fled to Moscow when rebels took Damascus in 2024.' },
  { n: 'Recep Tayyip Erdoğan', c: 'ruler', y: 'Turkey, 2003–', l: 'Islamist national conservatism', conf: 'high',
    v: [40, 90, 80, 85, 80, 40, 60, 70, 70, 20, 13],
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Party (Lührmann et al. 2020): AKP 2015, economy right (4.8 of 6), strong religious appeals, low commitment to pluralism, open to immigration', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.84 on a 0–2 scale (mean of 4 terms 2003–2018, rising from 0.13 to 1.47)'],
    note: 'Moved Turkey from a secular-military order toward Islamic conservatism; mass purges and jailing of journalists after the 2016 coup attempt; a presidential system with weak checks. Still wins contested elections.' },
  { n: 'Jair Bolsonaro', c: 'ruler', y: 'Brazil, 2019–2022', l: 'Right-wing populism', conf: 'high',
    v: [70, 60, 80, 70, 80, 60, 20, 90, 90, 50, -12],
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Party (Lührmann et al. 2020): PSL 2018, economy right (5.4 of 6), strong religious appeals, strongly anti-immigration', 'V-Dem v15, regime legitimation indicators (v2exl_legit*): conservative and religious legitimation', 'Global Populism Database v2.1 (Hawkins et al.): populism 0.50 on a 0–2 scale (2019–2022 term)'],
    note: 'Praised the military dictatorship, loosened gun laws, rolled back Amazon enforcement. Convicted by Brazil\'s Supreme Court in 2025 of plotting a coup after losing the 2022 election.' },
  { n: 'Rodrigo Duterte', c: 'ruler', y: 'Philippines, 2016–2022', l: 'Authoritarian populism', conf: 'high',
    v: [20, 85, 40, 50, -10, 20, 0, 100, null, 40, 53],
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Dem v15, regime legitimation indicators (v2exl_legit*)', 'Global Populism Database v2.1 (Hawkins et al.): populism 1.38 on a 0–2 scale (2016–2022 term)'],
    flag: 'V-Dem codes this regime as barely legitimized by any ideology; the scores describe what was done, not a coherent program.',
    note: 'Drug war in which police and vigilantes killed thousands; openly encouraged the killings. Feuded with the Catholic Church. Arrested in 2025 on an International Criminal Court warrant.' },
  { n: 'Lee Kuan Yew', c: 'ruler', y: 'Singapore, 1959–1990', l: 'Authoritarian developmentalism', conf: 'high',
    v: [15, 80, 60, 40, -30, -20, 30, 90, 40, -30, null],
    src: ['Herre (2023), Global Leader Ideologies: coded leftist (the PAP sat in the Socialist International until 1976)', 'V-Party (Lührmann et al. 2020): People\'s Action Party, economy center-right (3.8 of 6), strongly secular', 'V-Dem v15, regime legitimation indicators (v2exl_legit*)'],
    note: 'Built Singapore into a trade hub with large state-owned firms and public housing for most citizens, but minimal welfare and tight control of unions. Caning, the death penalty for drug trafficking, press controls. Herre codes him leftist and V-Party codes his party center-right, so Economy sits near the middle.' },
  { n: 'Margaret Thatcher', c: 'leader', y: 'UK, 1979–1990', l: 'Thatcherism (neoliberal conservatism)', conf: 'high',
    v: [70, 40, 50, 50, 10, 30, 60, 70, 40, -80, null],
    src: ['Herre (2023), Global Leader Ideologies: coded rightist', 'V-Party (Lührmann et al. 2020): Conservatives 1979–87, economy 4.6 of 6, low religious appeals, immigration restrictive'],
    note: 'Privatization, broke the miners\' union, Falklands War, Section 28. Early to warn about climate change in 1989, before turning skeptical of the politics around it.' },

  // ---- Celebrities and notorious figures ----
  { n: 'Sean "Diddy" Combs', c: 'public', y: 'Music mogul', l: 'Democratic-aligned Black economic empowerment', conf: 'low',
    v: [20, null, -20, null, null, -40, null, null, null, -20, null],
    src: ['No scholarly coding exists; based on journalism and the person\'s own public statements.'],
    note: 'Ran the "Vote or Die" turnout campaign in 2004; endorsed Obama and Biden, then said in 2020 that Black votes "aren\'t free" and must be earned with policy. Built a business brand around Black ownership. Convicted in 2025 on federal Mann Act charges; acquitted of racketeering and sex trafficking. Little stated policy beyond this, so most axes are blank.' },
  { n: 'Jeffrey Epstein', c: 'public', y: 'Financier', l: 'No stated ideology (donor to both parties)', conf: 'low',
    v: [40, null, null, -30, null, null, null, null, null, null, null],
    src: ['No scholarly coding exists; based on journalism and the person\'s own public statements.'],
    note: 'Donated mainly to Democrats and occasionally Republicans; cultivated politicians of both parties and foreign leaders. Ran his money through US Virgin Islands tax structures. The New York Times reported he talked of seeding the human race with his DNA. Pleaded guilty in 2008 to Florida charges including procuring a minor for prostitution; died in jail in 2019 awaiting trial on federal sex-trafficking charges. Too little record for an overall match.' },
  { n: 'Kanye West (Ye)', c: 'public', y: 'Musician', l: 'Erratic religious conservatism', conf: 'low',
    v: [30, null, 60, 40, 70, 60, null, null, null, null, null],
    src: ['No scholarly coding exists; based on journalism and the person\'s own public statements.'],
    note: 'Backed Trump, ran for president in 2020 on a Christian platform opposing abortion; repeated antisemitic statements from 2022 onward. Positions shift often.' },
  { n: 'Elon Musk', c: 'public', y: 'Businessman', l: 'Tech-right populism', conf: 'medium',
    v: [50, 20, 30, 40, -10, 40, 0, 60, 10, 0, null],
    src: ['No scholarly coding exists; based on journalism and the person\'s own public statements.'],
    note: 'Moved from Obama-era donor to Trump\'s largest 2024 backer and head of DOGE federal cost cutting. Backs Germany\'s AfD; frames speech moderation as censorship. Built his fortune on electric cars and solar while opposing EV subsidies.' },
  { n: 'Joe Rogan', c: 'public', y: 'Podcaster', l: 'Heterodox libertarian-leaning', conf: 'low',
    v: [0, -60, 0, 20, -30, -10, -40, 10, null, -30, null],
    src: ['No scholarly coding exists; based on journalism and the person\'s own public statements.'],
    note: 'Endorsed Bernie Sanders in 2020 and Trump in 2024. Favors drug legalization and gun rights; opposed COVID mandates and transgender women competing in women\'s sports.' },
  { n: 'Andrew Tate', c: 'public', y: 'Influencer', l: 'Reactionary "manosphere" traditionalism', conf: 'low',
    v: [60, 30, 90, 40, 60, 20, null, 80, null, 30, null],
    src: ['No scholarly coding exists; based on journalism and the person\'s own public statements.'],
    note: 'Promotes male dominance and traditional gender roles; converted to Islam in 2022. Calls the global system "the Matrix." Faces rape and human-trafficking charges in Romania and the UK, which he denies.' }
];
