// Figure profiles. Vector order: econ, power, culture, nation, faith, belong, war, justice, ecology, method.
// Scores place each person on the present-day spectrum (the one the test-taker answers on), from what
// they did and said publicly, not relative to their own era.
// null = no usable public record on that axis; the axis is skipped for that person.
// conf: how much documented political record the estimate rests on (high / medium / low).
const FIGURE_CATEGORIES = {
  militant: 'Militant & terrorist leaders',
  ruler: 'Dictators & heads of state',
  public: 'Celebrities & notorious figures'
};

const FIGURES = [
  // ---- Militant and terrorist leaders ----
  { n: 'Osama bin Laden', c: 'militant', y: 'al-Qaeda, 1988–2011', l: 'Salafi-jihadism', conf: 'high',
    v: [-10, 90, 100, -20, 100, 90, 95, 100, -30, 100],
    note: 'Founded al-Qaeda; ordered the 9/11 attacks. Called for a transnational caliphate under strict sharia. His statements attacked usury and, in 2010, blamed the West for climate change.' },
  { n: 'Ayman al-Zawahiri', c: 'militant', y: 'al-Qaeda, 2011–2022', l: 'Salafi-jihadism', conf: 'high',
    v: [-10, 90, 100, -20, 100, 90, 95, 100, null, 100],
    note: 'Egyptian Islamic Jihad founder, al-Qaeda\'s chief ideologue and later leader. Wrote "Knights Under the Prophet\'s Banner."' },
  { n: 'Abu Bakr al-Baghdadi', c: 'militant', y: 'ISIS, 2010–2019', l: 'Salafi-jihadism (takfiri)', conf: 'high',
    v: [null, 100, 100, -30, 100, 100, 100, 100, null, 100],
    note: 'Declared the ISIS caliphate in 2014. Genocide of Yazidis, mass executions of Shia and of Sunnis deemed apostates, sexual slavery.' },
  { n: 'Abu Musab al-Zarqawi', c: 'militant', y: 'al-Qaeda in Iraq, 2004–2006', l: 'Salafi-jihadism (takfiri)', conf: 'high',
    v: [null, 95, 100, -20, 100, 100, 100, 100, null, 100],
    note: 'Led al-Qaeda in Iraq; deliberately targeted Shia civilians to start a sectarian war. The organization became ISIS.' },
  { n: 'Mullah Omar', c: 'militant', y: 'Taliban, 1994–2013', l: 'Deobandi Islamism', conf: 'medium',
    v: [null, 95, 100, 40, 100, 80, 60, 100, null, 90],
    note: 'Founded the Taliban; as emir ran Afghanistan under strict sharia, banned girls\' schooling, destroyed the Bamiyan Buddhas, sheltered bin Laden. Goals were mostly confined to Afghanistan.' },
  { n: 'Abubakar Shekau', c: 'militant', y: 'Boko Haram, 2009–2021', l: 'Salafi-jihadism', conf: 'medium',
    v: [null, 100, 100, -10, 100, 100, 100, 100, null, 100],
    note: 'Led Boko Haram, whose name rejects Western education; the Chibok kidnapping of 276 schoolgirls, mass killings of Muslims and Christians.' },
  { n: 'Hassan Nasrallah', c: 'militant', y: 'Hezbollah, 1992–2024', l: 'Khomeinism', conf: 'high',
    v: [-20, 70, 80, 40, 95, 50, 80, 70, null, 70],
    note: 'Led Hezbollah\'s militia and its political party, which sat in Lebanon\'s parliament and cabinets. Loyal to Iran\'s Supreme Leader; ran a large social-services network.' },
  { n: 'Yahya Sinwar', c: 'militant', y: 'Hamas, 2017–2024', l: 'Islamist nationalism', conf: 'high',
    v: [null, 80, 85, 80, 95, 85, 95, 90, null, 100],
    note: 'Hamas leader in Gaza and planner of the October 7, 2023 attack. Known earlier for executing suspected collaborators.' },
  { n: 'Abimael Guzmán', c: 'militant', y: 'Shining Path, 1969–1992', l: 'Maoism ("Gonzalo Thought")', conf: 'high',
    v: [-100, 100, -20, 0, -100, 20, 90, 90, null, 100],
    note: 'Philosophy professor who launched a people\'s war in Peru; massacres of peasants who resisted. The Truth Commission attributed about half of some 69,000 deaths in the conflict to the Shining Path.' },
  { n: 'Ulrike Meinhof', c: 'militant', y: 'Red Army Faction, 1970–1976', l: 'Anti-imperialist Marxism', conf: 'medium',
    v: [-90, 0, -70, -80, -80, -60, -50, null, null, 95],
    note: 'Left-wing journalist turned co-founder of the Baader-Meinhof Group: bombings and kidnappings against West German institutions and US bases, framed as resistance to the Vietnam War.' },
  { n: 'George Habash', c: 'militant', y: 'PFLP, 1967–2000', l: 'Revolutionary Marxist nationalism', conf: 'medium',
    v: [-85, 60, -30, 80, -70, 20, 80, null, null, 100],
    note: 'Christian-born founder of the Popular Front for the Liberation of Palestine; pioneered airliner hijackings in 1968–70.' },
  { n: 'Abdullah Öcalan', c: 'militant', y: 'PKK, 1978–', l: 'Democratic confederalism (earlier Marxism-Leninism)', conf: 'medium',
    v: [-70, -40, -70, 30, -50, -40, 40, -30, -70, 70],
    note: 'Founded the PKK as a Marxist-Leninist separatist guerrilla army. Imprisoned since 1999, he rewrote its aims around stateless local democracy, women\'s liberation and ecology. Called for the PKK to disarm in 2025. Scored on his later thought.' },
  { n: 'Velupillai Prabhakaran', c: 'militant', y: 'LTTE, 1976–2009', l: 'Tamil militant separatism', conf: 'medium',
    v: [-40, 90, -10, 100, -30, 70, 95, 90, null, 100],
    note: 'Built the Tamil Tigers into a conventional army with a navy; pioneered suicide bombings, assassinated Rajiv Gandhi, expelled Muslims from the north.' },
  { n: 'Shoko Asahara', c: 'militant', y: 'Aum Shinrikyo, 1987–1995', l: 'Apocalyptic religious cult', conf: 'medium',
    v: [null, 100, null, -40, 100, 60, 90, null, null, 100],
    note: 'Guru who blended Buddhist, Hindu and Christian apocalypticism; ordered the 1995 sarin attack on the Tokyo subway. Ran in the 1990 Japanese election before turning to violence.' },
  { n: 'Ted Kaczynski', c: 'militant', y: 'Unabomber, 1978–1995', l: 'Anti-technology anarcho-primitivism', conf: 'high',
    v: [-20, -60, 30, null, -30, null, null, null, -100, 100],
    note: 'His manifesto, "Industrial Society and Its Future," calls for revolution against the industrial-technological system and spends long sections attacking leftism.' },
  { n: 'Timothy McVeigh', c: 'militant', y: 'Oklahoma City bombing, 1995', l: 'Anti-government militia movement', conf: 'medium',
    v: [50, -90, 30, 50, -10, 40, -60, null, null, 100],
    note: 'Gulf War veteran radicalized by Ruby Ridge and Waco; bombed a federal building, killing 168. Gun-rights absolutist influenced by "The Turner Diaries."' },
  { n: 'Anders Breivik', c: 'militant', y: 'Norway attacks, 2011', l: 'Counter-jihad ethnonationalism', conf: 'high',
    v: [30, 60, 90, 90, 40, 100, 80, 80, null, 100],
    note: 'Murdered 77 people, mostly teenagers at a Labour Party youth camp. His manifesto attacks "cultural Marxism," Islam and multiculturalism and calls for cultural Christianity.' },
  { n: 'Joseph Kony', c: 'militant', y: 'Lord\'s Resistance Army, 1987–', l: 'Millenarian Christian militancy', conf: 'low',
    v: [null, 100, null, null, 90, null, 100, 100, null, 100],
    note: 'Claims to channel spirits and to fight for rule by the Ten Commandments. Abducted tens of thousands of children as soldiers and sex slaves. Little coherent program beyond that.' },

  // ---- Dictators and heads of state ----
  { n: 'Vladimir Lenin', c: 'ruler', y: 'Soviet Russia, 1917–1924', l: 'Marxism-Leninism', conf: 'high',
    v: [-95, 85, -50, -80, -100, -30, 60, 80, 60, 100],
    note: 'Led the October Revolution; founded the one-party state and the Cheka. Legalized abortion and divorce early on. Expected world revolution.' },
  { n: 'Joseph Stalin', c: 'ruler', y: 'USSR, 1924–1953', l: 'Marxism-Leninism (Stalinism)', conf: 'high',
    v: [-100, 100, 30, 60, -100, 60, 80, 100, 90, 90],
    note: 'Forced collectivization, the Great Terror, the Gulag, deportation of whole nationalities. Reversed early Soviet social liberalism; "socialism in one country."' },
  { n: 'Mao Zedong', c: 'ruler', y: 'PRC, 1949–1976', l: 'Maoism', conf: 'high',
    v: [-100, 100, -40, 40, -100, 30, 70, 90, 90, 100],
    note: 'Great Leap Forward famine, the Cultural Revolution against "the Four Olds." "Political power grows out of the barrel of a gun."' },
  { n: 'Pol Pot', c: 'ruler', y: 'Khmer Rouge, 1975–1979', l: 'Agrarian Maoism', conf: 'high',
    v: [-100, 100, -20, 100, -100, 90, 80, 100, -60, 100],
    note: 'Emptied the cities, abolished money and religion, killed roughly a quarter of Cambodia\'s population. Targeted Vietnamese, Cham and Chinese minorities.' },
  { n: 'Adolf Hitler', c: 'ruler', y: 'Germany, 1933–1945', l: 'National Socialism', conf: 'high',
    v: [0, 100, 70, 100, 10, 100, 100, 100, 30, 90],
    note: 'Totalitarian racial state, the Holocaust, wars of conquest. Private property kept under heavy state direction.' },
  { n: 'Benito Mussolini', c: 'ruler', y: 'Italy, 1922–1943', l: 'Fascism', conf: 'high',
    v: [10, 95, 60, 100, 20, 70, 95, 90, 60, 80],
    note: 'Coined "fascism," took power after the March on Rome, built the corporatist one-party state, invaded Ethiopia. Racial laws from 1938.' },
  { n: 'Francisco Franco', c: 'ruler', y: 'Spain, 1939–1975', l: 'National Catholicism', conf: 'high',
    v: [20, 90, 90, 90, 90, 60, 60, 95, null, 80],
    note: 'Won the Civil War after a military coup; Catholic Church restored as state religion, regional languages suppressed. Market liberalization from 1959.' },
  { n: 'Augusto Pinochet', c: 'ruler', y: 'Chile, 1973–1990', l: 'Authoritarian free-market conservatism', conf: 'high',
    v: [80, 90, 70, 70, 40, 30, 60, 95, null, 80],
    note: 'Seized power in a coup; the "Chicago Boys" privatization program; thousands killed or disappeared. Stepped down after losing the 1988 plebiscite.' },
  { n: 'Fidel Castro', c: 'ruler', y: 'Cuba, 1959–2008', l: 'Marxism-Leninism', conf: 'high',
    v: [-90, 90, -10, 50, -70, -10, 60, 80, 40, 100],
    note: 'Took power by guerrilla war; nationalized the economy, one-party rule, sent troops to Angola. Persecuted gay men in the UMAP camps, later apologized.' },
  { n: 'Che Guevara', c: 'ruler', y: 'Cuba, 1959–1965', l: 'Guevarism (guerrilla Marxism)', conf: 'high',
    v: [-95, 80, -30, -60, -80, -10, 90, 90, null, 100],
    note: 'Argentine revolutionary who oversaw executions at La Cabaña and pushed rapid nationalization. Called for "two, three, many Vietnams." Killed in Bolivia trying to export the revolution.' },
  { n: 'Ruhollah Khomeini', c: 'ruler', y: 'Iran, 1979–1989', l: 'Khomeinism', conf: 'high',
    v: [-30, 90, 95, 60, 100, 70, 70, 95, null, 90],
    note: 'Led the Islamic Revolution, created rule of the jurist, the fatwa against Salman Rushdie, mass executions of prisoners in 1988.' },
  { n: 'Kim Jong Un', c: 'ruler', y: 'North Korea, 2011–', l: 'Juche', conf: 'high',
    v: [-80, 100, 50, 100, -60, 80, 90, 100, 70, null],
    note: 'Third hereditary leader; nuclear and missile program, executions of his uncle and others, total control of information.' },
  { n: 'Vladimir Putin', c: 'ruler', y: 'Russia, 1999–', l: 'Authoritarian national conservatism', conf: 'high',
    v: [30, 85, 70, 90, 50, 40, 85, 80, 80, 20],
    note: 'Invaded Ukraine in 2014 and 2022, "gay propaganda" laws, alliance with the Orthodox Church, oil-and-gas state economy, jailed and killed opponents.' },
  { n: 'Xi Jinping', c: 'ruler', y: 'China, 2012–', l: 'Marxism-Leninism with Chinese characteristics', conf: 'high',
    v: [-40, 95, 30, 70, -80, 50, 50, 80, 30, -30],
    note: 'Ended term limits, mass internment of Uyghurs, "common prosperity," tightened control of private firms. Promotes "ecological civilization" while expanding coal.' },
  { n: 'Maximilien Robespierre', c: 'ruler', y: 'France, 1793–1794', l: 'Jacobinism', conf: 'medium',
    v: [-40, 90, -60, 60, -20, 0, 60, 100, null, 100],
    note: 'Leading figure of the Committee of Public Safety during the Terror. Argued against slavery and for universal male suffrage; backed price controls. Replaced Catholic worship with the deist Cult of the Supreme Being.' },
  { n: 'Saddam Hussein', c: 'ruler', y: 'Iraq, 1979–2003', l: 'Ba\'athism', conf: 'high',
    v: [-40, 100, 30, 90, 20, 90, 95, 100, 70, 90],
    note: 'Secular pan-Arab socialist one-party state, later an Islamic "Faith Campaign." Invaded Iran and Kuwait; the Anfal campaign and the Halabja gas attack against Kurds.' },
  { n: 'Muammar Gaddafi', c: 'ruler', y: 'Libya, 1969–2011', l: 'Third International Theory', conf: 'high',
    v: [-70, 95, 50, 60, 40, 40, 70, 95, 60, 90],
    note: 'Took power in a coup; the Green Book\'s "Islamic socialism" and nominal rule by people\'s committees. Sponsored the Lockerbie bombing and foreign militant groups.' },
  { n: 'Idi Amin', c: 'ruler', y: 'Uganda, 1971–1979', l: 'Military dictatorship', conf: 'medium',
    v: [-20, 100, null, 90, 50, 100, 80, 100, null, 90],
    note: 'Seized power in a coup, expelled Uganda\'s roughly 80,000 Asians in 1972, killed an estimated 100,000 to 500,000 people. Invaded Tanzania, which ended his rule.' },
  { n: 'Robert Mugabe', c: 'ruler', y: 'Zimbabwe, 1980–2017', l: 'African nationalist socialism', conf: 'high',
    v: [-50, 90, 80, 90, 40, 80, 40, 80, null, 80],
    note: 'Guerrilla leader turned president. Gukurahundi massacres in Matabeleland, seizure of white-owned farms, hyperinflation. Called gay people "worse than dogs and pigs."' },
  { n: 'Hugo Chávez', c: 'ruler', y: 'Venezuela, 1999–2013', l: 'Bolivarian socialism', conf: 'high',
    v: [-75, 70, 0, 70, 20, -20, 30, 30, 60, 40],
    note: 'Led a failed coup in 1992, then won elections. Nationalized oil, steel and utilities, funded social programs with oil revenue, packed the courts, closed RCTV.' },
  { n: 'Bashar al-Assad', c: 'ruler', y: 'Syria, 2000–2024', l: 'Ba\'athism', conf: 'high',
    v: [-10, 100, 20, 80, -60, 50, 60, 100, null, null],
    note: 'Inherited power from his father. Met the 2011 uprising with barrel bombs, chemical weapons and mass torture in prisons. Fled to Moscow when rebels took Damascus in 2024.' },
  { n: 'Recep Tayyip Erdoğan', c: 'ruler', y: 'Turkey, 2003–', l: 'Islamist national conservatism', conf: 'high',
    v: [30, 80, 70, 85, 70, 50, 60, 70, 70, -10],
    note: 'Moved Turkey from a secular-military order toward Islamic conservatism; mass purges and jailing of journalists after the 2016 coup attempt; a presidential system with weak checks. Still wins contested elections.' },
  { n: 'Jair Bolsonaro', c: 'ruler', y: 'Brazil, 2019–2022', l: 'Right-wing populism', conf: 'high',
    v: [50, 60, 80, 70, 70, 30, 20, 90, 90, 60],
    note: 'Praised the military dictatorship, loosened gun laws, rolled back Amazon enforcement. Convicted by Brazil\'s Supreme Court in 2025 of plotting a coup after losing the 2022 election.' },
  { n: 'Rodrigo Duterte', c: 'ruler', y: 'Philippines, 2016–2022', l: 'Authoritarian populism', conf: 'high',
    v: [0, 85, 40, 50, -10, 20, 0, 100, null, 40],
    note: 'Drug war in which police and vigilantes killed thousands; openly encouraged the killings. Feuded with the Catholic Church. Arrested in 2025 on an International Criminal Court warrant.' },
  { n: 'Lee Kuan Yew', c: 'ruler', y: 'Singapore, 1959–1990', l: 'Authoritarian developmentalism', conf: 'high',
    v: [50, 80, 50, 40, -30, -20, 30, 90, 40, -30],
    note: 'Built Singapore into a trade hub; caning and the death penalty for drug trafficking, press controls, enforced ethnic quotas in public housing.' },
  { n: 'Margaret Thatcher', c: 'ruler', y: 'UK, 1979–1990', l: 'Thatcherism (neoliberal conservatism)', conf: 'high',
    v: [80, 40, 50, 50, 30, 10, 60, 70, 40, -80],
    note: 'Privatization, broke the miners\' union, Falklands War, Section 28. Early to warn about climate change in 1989, before turning skeptical of the politics around it.' },

  // ---- Celebrities and notorious figures ----
  { n: 'Sean "Diddy" Combs', c: 'public', y: 'Music mogul', l: 'Democratic-aligned Black economic empowerment', conf: 'low',
    v: [20, null, -20, null, null, -40, null, null, null, -20],
    note: 'Ran the "Vote or Die" turnout campaign in 2004; endorsed Obama and Biden, then said in 2020 that Black votes "aren\'t free" and must be earned with policy. Built a business brand around Black ownership. Convicted in 2025 on federal Mann Act charges; acquitted of racketeering and sex trafficking. Little stated policy beyond this, so most axes are blank.' },
  { n: 'Jeffrey Epstein', c: 'public', y: 'Financier', l: 'No stated ideology (donor to both parties)', conf: 'low',
    v: [40, null, null, -30, null, null, null, null, null, null],
    note: 'Donated mainly to Democrats and occasionally Republicans; cultivated politicians of both parties and foreign leaders. Ran his money through US Virgin Islands tax structures. The New York Times reported he talked of seeding the human race with his DNA. Pleaded guilty in 2008 to Florida charges including procuring a minor for prostitution; died in jail in 2019 awaiting trial on federal sex-trafficking charges. Too little record for an overall match.' },
  { n: 'Kanye West (Ye)', c: 'public', y: 'Musician', l: 'Erratic religious conservatism', conf: 'low',
    v: [30, null, 60, 40, 70, 60, null, null, null, null],
    note: 'Backed Trump, ran for president in 2020 on a Christian platform opposing abortion; repeated antisemitic statements from 2022 onward. Positions shift often.' },
  { n: 'Elon Musk', c: 'public', y: 'Businessman', l: 'Tech-right populism', conf: 'medium',
    v: [50, 20, 30, 40, -10, 40, 0, 60, 10, 0],
    note: 'Moved from Obama-era donor to Trump\'s largest 2024 backer and head of DOGE federal cost cutting. Backs Germany\'s AfD; frames speech moderation as censorship. Built his fortune on electric cars and solar while opposing EV subsidies.' },
  { n: 'Joe Rogan', c: 'public', y: 'Podcaster', l: 'Heterodox libertarian-leaning', conf: 'low',
    v: [0, -60, 0, 20, -30, -10, -40, 10, null, -30],
    note: 'Endorsed Bernie Sanders in 2020 and Trump in 2024. Favors drug legalization and gun rights; opposed COVID mandates and transgender women competing in women\'s sports.' },
  { n: 'Andrew Tate', c: 'public', y: 'Influencer', l: 'Reactionary "manosphere" traditionalism', conf: 'low',
    v: [60, 30, 90, 40, 60, 20, null, 80, null, 30],
    note: 'Promotes male dominance and traditional gender roles; converted to Islam in 2022. Calls the global system "the Matrix." Faces rape and human-trafficking charges in Romania and the UK, which he denies.' }
];
