// Figure profiles. Vector order: econ, power, culture, nation, faith, belong, war, justice, ecology, method.
// Scores place each person on the present-day spectrum (the one the test-taker answers on), from what
// they did and said publicly, not relative to their own era. A 19th-century president who enslaved people
// scores high on Exclusion because that is where the position sits today.
// null = no usable public record on that axis; the axis is skipped for that person.
// conf: how much documented political record the estimate rests on (high / medium / low).
const FIGURE_CATEGORIES = {
  president: 'US presidents',
  militant: 'Militant & terrorist leaders',
  ruler: 'Dictators & heads of state',
  activist: 'Politicians & activists',
  public: 'Celebrities & notorious figures'
};

const FIGURES = [
  // ---- US presidents, in order ----
  { n: 'George Washington', c: 'president', y: '1789–1797', l: 'Federalist-leaning nonpartisan', conf: 'medium',
    v: [40, 20, 70, 60, 30, 60, 10, 60, 30, 20],
    note: 'Backed Hamilton\'s national bank and assumption of debts, proclaimed neutrality in Europe\'s wars, crushed the Whiskey Rebellion. Enslaved over 100 people; freed them in his will. Led an armed revolution before taking office.' },
  { n: 'John Adams', c: 'president', y: '1797–1801', l: 'Federalist', conf: 'medium',
    v: [30, 55, 70, 50, 45, 40, 20, 60, null, 0],
    note: 'Signed the Alien and Sedition Acts, used to prosecute critical newspaper editors. Fought an undeclared naval war with France but avoided full war. Never owned enslaved people.' },
  { n: 'Thomas Jefferson', c: 'president', y: '1801–1809', l: 'Democratic-Republican', conf: 'high',
    v: [30, -60, 40, 30, -60, 65, 0, 40, 0, 50],
    note: 'Author of the Virginia Statute for Religious Freedom; championed small government and yeoman farmers. Enslaved over 600 people over his life and wrote of Black inferiority. "The tree of liberty must be refreshed from time to time with the blood of patriots."' },
  { n: 'James Madison', c: 'president', y: '1809–1817', l: 'Democratic-Republican', conf: 'medium',
    v: [30, -20, 50, 40, -50, 55, 30, 40, null, 10],
    note: 'Architect of the Constitution and Bill of Rights, strict on church-state separation. Led the country into the War of 1812. Enslaver.' },
  { n: 'James Monroe', c: 'president', y: '1817–1825', l: 'Democratic-Republican', conf: 'medium',
    v: [30, 10, 55, 60, 0, 55, 30, null, null, 0],
    note: 'Monroe Doctrine: the Americas closed to European colonization. Enslaver; backed colonization of freed Black Americans in Liberia.' },
  { n: 'John Quincy Adams', c: 'president', y: '1825–1829', l: 'National Republican', conf: 'medium',
    v: [10, 30, 40, 40, 30, 10, 0, null, 50, -60],
    note: 'Pushed federal roads, canals and a national university. Later in Congress the leading opponent of the gag rule on slavery petitions; argued the Amistad case.' },
  { n: 'Andrew Jackson', c: 'president', y: '1829–1837', l: 'Jacksonian Democrat', conf: 'high',
    v: [40, 50, 60, 80, 10, 90, 70, 70, 40, 30],
    note: 'Killed the Second Bank, signed the Indian Removal Act leading to the Trail of Tears, ignored the Supreme Court in Worcester v. Georgia. Enslaver.' },
  { n: 'Martin Van Buren', c: 'president', y: '1837–1841', l: 'Jacksonian Democrat; later Free Soil', conf: 'medium',
    v: [50, 0, 50, 40, 0, 70, 10, null, null, -20],
    note: 'Carried out Cherokee removal and refused to annex Texas. Ran in 1848 on the anti-slavery-expansion Free Soil ticket.' },
  { n: 'William Henry Harrison', c: 'president', y: '1841', l: 'Whig', conf: 'low',
    v: [30, 0, 60, 50, 10, 70, 60, null, null, 0],
    note: 'Died a month into office. Career defined by wars against Native nations (Tippecanoe) and treaties taking their land.' },
  { n: 'John Tyler', c: 'president', y: '1841–1845', l: 'States\'-rights Democrat', conf: 'medium',
    v: [50, -20, 70, 60, 10, 90, 40, null, null, 40],
    note: 'Vetoed the Whig bank bills, annexed Texas as a slave state. Later elected to the Confederate Congress.' },
  { n: 'James K. Polk', c: 'president', y: '1845–1849', l: 'Jacksonian Democrat', conf: 'high',
    v: [40, 20, 60, 90, 10, 85, 85, null, null, 0],
    note: 'Manifest Destiny: provoked and won the Mexican-American War, taking about half of Mexico. Lowered tariffs. Enslaver.' },
  { n: 'Zachary Taylor', c: 'president', y: '1849–1850', l: 'Whig', conf: 'low',
    v: [20, 10, 60, 50, 0, 70, 50, null, null, -20],
    note: 'Career general and enslaver who nonetheless threatened to hang secessionists and opposed slavery\'s spread into new territories.' },
  { n: 'Millard Fillmore', c: 'president', y: '1850–1853', l: 'Whig; later Know-Nothing', conf: 'medium',
    v: [30, 20, 60, 60, 30, 75, 10, null, null, -30],
    note: 'Signed the Fugitive Slave Act. Ran in 1856 for the anti-Catholic, anti-immigrant American (Know-Nothing) Party.' },
  { n: 'Franklin Pierce', c: 'president', y: '1853–1857', l: 'Northern pro-slavery Democrat', conf: 'medium',
    v: [40, 10, 60, 70, 0, 80, 40, null, null, 0],
    note: 'Signed the Kansas-Nebraska Act; his envoys drafted the Ostend Manifesto on acquiring Cuba.' },
  { n: 'James Buchanan', c: 'president', y: '1857–1861', l: 'Pro-Southern Democrat', conf: 'medium',
    v: [40, 20, 60, 60, 10, 85, 20, null, null, -10],
    note: 'Pressed for the Dred Scott outcome and the pro-slavery Lecompton constitution; held that secession was illegal but that he could not stop it.' },
  { n: 'Abraham Lincoln', c: 'president', y: '1861–1865', l: 'Republican (Whig roots)', conf: 'high',
    v: [10, 50, 40, 60, 20, 10, 60, 40, 60, -30],
    note: 'Won the Civil War, issued the Emancipation Proclamation, pushed the 13th Amendment. Suspended habeas corpus. Backed tariffs, railroads and the Homestead Act. Held some racial views that would be disqualifying today.' },
  { n: 'Andrew Johnson', c: 'president', y: '1865–1869', l: 'War Democrat / Unionist', conf: 'high',
    v: [30, 0, 60, 50, 10, 90, 0, null, null, 0],
    note: 'Vetoed the Civil Rights Act of 1866 and the Freedmen\'s Bureau bill; pardoned Confederates en masse. Impeached, acquitted by one vote.' },
  { n: 'Ulysses S. Grant', c: 'president', y: '1869–1877', l: 'Republican', conf: 'high',
    v: [20, 40, 30, 50, 10, -10, 30, 50, 50, -40],
    note: 'Enforced Reconstruction, used federal troops and courts to break the first Ku Klux Klan. His administration also waged the later Plains wars.' },
  { n: 'Rutherford B. Hayes', c: 'president', y: '1877–1881', l: 'Republican', conf: 'medium',
    v: [30, 0, 50, 40, 30, 30, 10, null, null, -40],
    note: 'Withdrew federal troops from the South, ending Reconstruction. Used troops against the 1877 railroad strike.' },
  { n: 'James A. Garfield', c: 'president', y: '1881', l: 'Republican', conf: 'low',
    v: [30, 0, 40, 40, 30, 0, null, null, null, -40],
    note: 'Assassinated months into office. Strong advocate of Black suffrage and education.' },
  { n: 'Chester A. Arthur', c: 'president', y: '1881–1885', l: 'Republican', conf: 'medium',
    v: [20, 0, 40, 40, 10, 40, null, null, null, -50],
    note: 'Signed the Pendleton civil-service reform and, after a first veto, the Chinese Exclusion Act.' },
  { n: 'Grover Cleveland', c: 'president', y: '1885–1889, 1893–1897', l: 'Bourbon Democrat', conf: 'high',
    v: [60, -20, 50, 40, 20, 40, -30, null, null, -50],
    note: 'Gold standard, low tariffs, record vetoes of spending bills. Sent troops to break the Pullman strike. Refused to annex Hawaii after the coup.' },
  { n: 'Benjamin Harrison', c: 'president', y: '1889–1893', l: 'Republican', conf: 'medium',
    v: [30, 20, 50, 70, 20, 30, 30, null, 40, -50],
    note: 'Signed the McKinley Tariff and Sherman Antitrust Act; backed federal protection of Black voting rights, which failed in the Senate.' },
  { n: 'William McKinley', c: 'president', y: '1897–1901', l: 'Republican', conf: 'medium',
    v: [40, 20, 50, 60, 30, 30, 60, null, 60, -50],
    note: 'High tariffs and gold standard. Fought the Spanish-American War, annexed the Philippines, Puerto Rico, Guam and Hawaii.' },
  { n: 'Theodore Roosevelt', c: 'president', y: '1901–1909', l: 'Progressive Republican', conf: 'high',
    v: [-10, 50, 30, 60, 20, 30, 80, 50, -60, -40],
    note: 'Trust-busting, the Square Deal, 230 million acres of public lands protected. "Speak softly and carry a big stick." Ran in 1912 on a platform including social insurance.' },
  { n: 'William Howard Taft', c: 'president', y: '1909–1913', l: 'Conservative Republican', conf: 'medium',
    v: [40, 10, 40, 50, 0, 20, 20, 40, 30, -80],
    note: 'Brought more antitrust suits than T. Roosevelt but was a legalist by temperament; later Chief Justice. Dollar diplomacy.' },
  { n: 'Woodrow Wilson', c: 'president', y: '1913–1921', l: 'Progressive Democrat', conf: 'high',
    v: [-10, 60, 40, -50, 30, 75, 40, 50, null, -30],
    note: 'Created the Federal Reserve and income tax, designed the League of Nations. Resegregated the federal civil service; Espionage and Sedition Acts jailed war critics.' },
  { n: 'Warren G. Harding', c: 'president', y: '1921–1923', l: 'Republican', conf: 'medium',
    v: [50, 0, 40, 60, 10, 30, -20, null, null, -40],
    note: '"Return to normalcy": tax cuts, tariff increases, the Washington Naval disarmament conference. Spoke for Black civil rights in Birmingham in 1921 and signed early immigration quotas.' },
  { n: 'Calvin Coolidge', c: 'president', y: '1923–1929', l: 'Conservative Republican', conf: 'high',
    v: [75, -10, 50, 50, 20, 50, -20, null, null, -70],
    note: 'Small government, tax cuts, vetoed farm subsidies. Signed the 1924 Immigration Act with its national-origins quotas.' },
  { n: 'Herbert Hoover', c: 'president', y: '1929–1933', l: 'Progressive-turned-conservative Republican', conf: 'high',
    v: [40, 0, 40, 50, 10, 40, -30, 40, 40, -60],
    note: 'Signed Smoot-Hawley tariffs; resisted direct federal relief during the Depression. Oversaw deportations of Mexicans and Mexican Americans.' },
  { n: 'Franklin D. Roosevelt', c: 'president', y: '1933–1945', l: 'New Deal liberal', conf: 'high',
    v: [-60, 50, 0, 10, 10, 50, 60, 40, -20, -30],
    note: 'New Deal, Social Security, Wagner Act, Civilian Conservation Corps. Led the US through WWII. Ordered internment of Japanese Americans; tried to pack the Supreme Court.' },
  { n: 'Harry S. Truman', c: 'president', y: '1945–1953', l: 'Fair Deal Democrat', conf: 'high',
    v: [-40, 30, 0, -40, 20, 0, 70, 40, 40, -60],
    note: 'Dropped the atomic bombs, founded NATO, fought in Korea, desegregated the armed forces. Proposed national health insurance.' },
  { n: 'Dwight D. Eisenhower', c: 'president', y: '1953–1961', l: 'Moderate Republican', conf: 'high',
    v: [10, 10, 30, -10, 40, 10, 30, 40, 40, -80],
    note: 'Kept New Deal programs, built the Interstate system, sent troops to Little Rock, warned of the military-industrial complex. Added "under God" to the Pledge. CIA coups in Iran and Guatemala.' },
  { n: 'John F. Kennedy', c: 'president', y: '1961–1963', l: 'Cold War liberal', conf: 'high',
    v: [-20, 10, 0, -30, 10, -20, 60, null, null, -70],
    note: 'Bay of Pigs, Cuban Missile Crisis, escalation in Vietnam; proposed the Civil Rights Act and tax cuts.' },
  { n: 'Lyndon B. Johnson', c: 'president', y: '1963–1969', l: 'Great Society liberal', conf: 'high',
    v: [-60, 20, -20, -20, 20, -60, 75, 30, -20, -70],
    note: 'Civil Rights Act, Voting Rights Act, Medicare, Medicaid, the 1965 immigration reform. Massive escalation of the Vietnam War.' },
  { n: 'Richard Nixon', c: 'president', y: '1969–1974', l: 'Moderate-to-conservative Republican', conf: 'high',
    v: [-10, 60, 30, 10, 10, 10, 60, 70, -40, 10],
    note: 'Created the EPA, imposed wage-price controls, opened to China, launched the war on drugs, bombed Cambodia. Resigned over Watergate.' },
  { n: 'Gerald Ford', c: 'president', y: '1974–1977', l: 'Moderate Republican', conf: 'medium',
    v: [30, 0, 0, -10, 20, -20, 10, null, null, -80],
    note: 'Pardoned Nixon, signed the Helsinki Accords, supported the Equal Rights Amendment.' },
  { n: 'Jimmy Carter', c: 'president', y: '1977–1981', l: 'Moderate Democrat', conf: 'high',
    v: [-10, -10, 10, -50, 40, -50, -40, -10, -70, -90],
    note: 'Camp David Accords, human-rights foreign policy, solar panels on the White House, deregulated airlines and trucking. An evangelical Baptist.' },
  { n: 'Ronald Reagan', c: 'president', y: '1981–1989', l: 'Fusionist conservative', conf: 'high',
    v: [75, 20, 60, 40, 40, 0, 70, 70, 40, -60],
    note: 'Cut top tax rates from 70% to 28%, large defense buildup, war on drugs. Signed the 1986 amnesty for about 3 million undocumented immigrants.' },
  { n: 'George H. W. Bush', c: 'president', y: '1989–1993', l: 'Establishment Republican', conf: 'high',
    v: [40, 10, 40, -30, 30, -10, 60, 60, 20, -80],
    note: 'Gulf War coalition, Americans with Disabilities Act, Clean Air Act amendments, raised taxes despite "read my lips."' },
  { n: 'Bill Clinton', c: 'president', y: '1993–2001', l: 'New Democrat / Third Way', conf: 'high',
    v: [20, 10, -20, -60, 0, -40, 40, 60, -10, -80],
    note: 'NAFTA, welfare reform, the 1994 crime bill, balanced budgets, Defense of Marriage Act, Kosovo intervention.' },
  { n: 'George W. Bush', c: 'president', y: '2001–2009', l: 'Neoconservative / compassionate conservative', conf: 'high',
    v: [50, 50, 55, 20, 50, -10, 90, 70, 40, -60],
    note: 'Afghanistan and Iraq wars, the Patriot Act, warrantless surveillance, tax cuts, Medicare Part D, faith-based initiatives, pushed immigration reform.' },
  { n: 'Barack Obama', c: 'president', y: '2009–2017', l: 'Liberal Democrat', conf: 'high',
    v: [-30, 20, -50, -60, -20, -60, 40, -20, -60, -80],
    note: 'Affordable Care Act, Paris Agreement, Dodd-Frank, expanded drone strikes, Libya intervention, DACA. Came to back same-sex marriage in 2012.' },
  { n: 'Donald Trump', c: 'president', y: '2017–2021, 2025–', l: 'Right-wing populist / national conservative', conf: 'high',
    v: [20, 60, 50, 90, 30, 60, 30, 80, 90, 40],
    note: 'Broad tariffs, mass-deportation agenda, Paris withdrawal, tax cuts, appointed the justices who overturned Roe. Refused to accept the 2020 result; January 6.' },
  { n: 'Joe Biden', c: 'president', y: '2021–2025', l: 'Mainstream liberal Democrat', conf: 'high',
    v: [-40, 10, -50, -40, 10, -60, 10, -10, -60, -80],
    note: 'Inflation Reduction Act climate spending, infrastructure law, pro-union stance, Afghanistan withdrawal, military aid to Ukraine and Israel. Practicing Catholic.' },

  // ---- Militant and terrorist leaders ----
  { n: 'Osama bin Laden', c: 'militant', y: 'al-Qaeda, 1988–2011', l: 'Salafi-jihadism', conf: 'high',
    v: [-10, 90, 100, -20, 100, 90, 95, 100, -30, 100],
    note: 'Founded al-Qaeda; ordered the 9/11 attacks. Called for a transnational caliphate under strict sharia. His statements attacked usury and, in 2010, blamed the West for climate change.' },
  { n: 'Ayman al-Zawahiri', c: 'militant', y: 'al-Qaeda, 2011–2022', l: 'Salafi-jihadism', conf: 'high',
    v: [-10, 90, 100, -20, 100, 90, 95, 100, null, 100],
    note: 'Egyptian Islamic Jihad founder, al-Qaeda\'s chief ideologue and later leader. Wrote "Knights Under the Prophet\'s Banner."' },
  { n: 'Abu Bakr al-Baghdadi', c: 'militant', y: 'ISIS, 2010–2019', l: 'Salafi-jihadism (takfiri)', conf: 'high',
    v: [null, 100, 100, -30, 100, 100, 100, 100, null, 100],
    note: 'Declared the ISIS caliphate in 2014. Genocide of Yazidis, mass executions of Shia and of Sunnis deemed apostates, sexual slavery.' },
  { n: 'Abu Musab al-Zarqawi', c: 'militant', y: 'al-Qaeda in Iraq, 2004–2006', l: 'Salafi-jihadism (takfiri)', conf: 'high',
    v: [null, 95, 100, -20, 100, 100, 100, 100, null, 100],
    note: 'Led al-Qaeda in Iraq; deliberately targeted Shia civilians to start a sectarian war. The organization became ISIS.' },
  { n: 'Mullah Omar', c: 'militant', y: 'Taliban, 1994–2013', l: 'Deobandi Islamism', conf: 'medium',
    v: [null, 95, 100, 40, 100, 80, 60, 100, null, 90],
    note: 'Founded the Taliban; as emir ran Afghanistan under strict sharia, banned girls\' schooling, destroyed the Bamiyan Buddhas, sheltered bin Laden. Goals were mostly confined to Afghanistan.' },
  { n: 'Abubakar Shekau', c: 'militant', y: 'Boko Haram, 2009–2021', l: 'Salafi-jihadism', conf: 'medium',
    v: [null, 100, 100, -10, 100, 100, 100, 100, null, 100],
    note: 'Led Boko Haram, whose name rejects Western education; the Chibok kidnapping of 276 schoolgirls, mass killings of Muslims and Christians.' },
  { n: 'Hassan Nasrallah', c: 'militant', y: 'Hezbollah, 1992–2024', l: 'Khomeinism', conf: 'high',
    v: [-20, 70, 80, 40, 95, 50, 80, 70, null, 70],
    note: 'Led Hezbollah\'s militia and its political party, which sat in Lebanon\'s parliament and cabinets. Loyal to Iran\'s Supreme Leader; ran a large social-services network.' },
  { n: 'Yahya Sinwar', c: 'militant', y: 'Hamas, 2017–2024', l: 'Islamist nationalism', conf: 'high',
    v: [null, 80, 85, 80, 95, 85, 95, 90, null, 100],
    note: 'Hamas leader in Gaza and planner of the October 7, 2023 attack. Known earlier for executing suspected collaborators.' },
  { n: 'Abimael Guzmán', c: 'militant', y: 'Shining Path, 1969–1992', l: 'Maoism ("Gonzalo Thought")', conf: 'high',
    v: [-100, 100, -20, 0, -100, 20, 90, 90, null, 100],
    note: 'Philosophy professor who launched a people\'s war in Peru; massacres of peasants who resisted. The Truth Commission attributed about half of some 69,000 deaths in the conflict to the Shining Path.' },
  { n: 'Ulrike Meinhof', c: 'militant', y: 'Red Army Faction, 1970–1976', l: 'Anti-imperialist Marxism', conf: 'medium',
    v: [-90, 0, -70, -80, -80, -60, -50, null, null, 95],
    note: 'Left-wing journalist turned co-founder of the Baader-Meinhof Group: bombings and kidnappings against West German institutions and US bases, framed as resistance to the Vietnam War.' },
  { n: 'George Habash', c: 'militant', y: 'PFLP, 1967–2000', l: 'Revolutionary Marxist nationalism', conf: 'medium',
    v: [-85, 60, -30, 80, -70, 20, 80, null, null, 100],
    note: 'Christian-born founder of the Popular Front for the Liberation of Palestine; pioneered airliner hijackings in 1968–70.' },
  { n: 'Abdullah Öcalan', c: 'militant', y: 'PKK, 1978–', l: 'Democratic confederalism (earlier Marxism-Leninism)', conf: 'medium',
    v: [-70, -40, -70, 30, -50, -40, 40, -30, -70, 70],
    note: 'Founded the PKK as a Marxist-Leninist separatist guerrilla army. Imprisoned since 1999, he rewrote its aims around stateless local democracy, women\'s liberation and ecology. Called for the PKK to disarm in 2025. Scored on his later thought.' },
  { n: 'Velupillai Prabhakaran', c: 'militant', y: 'LTTE, 1976–2009', l: 'Tamil militant separatism', conf: 'medium',
    v: [-40, 90, -10, 100, -30, 70, 95, 90, null, 100],
    note: 'Built the Tamil Tigers into a conventional army with a navy; pioneered suicide bombings, assassinated Rajiv Gandhi, expelled Muslims from the north.' },
  { n: 'Shoko Asahara', c: 'militant', y: 'Aum Shinrikyo, 1987–1995', l: 'Apocalyptic religious cult', conf: 'medium',
    v: [null, 100, null, -40, 100, 60, 90, null, null, 100],
    note: 'Guru who blended Buddhist, Hindu and Christian apocalypticism; ordered the 1995 sarin attack on the Tokyo subway. Ran in the 1990 Japanese election before turning to violence.' },
  { n: 'Ted Kaczynski', c: 'militant', y: 'Unabomber, 1978–1995', l: 'Anti-technology anarcho-primitivism', conf: 'high',
    v: [-20, -60, 30, null, -30, null, null, null, -100, 100],
    note: 'His manifesto, "Industrial Society and Its Future," calls for revolution against the industrial-technological system and spends long sections attacking leftism.' },
  { n: 'Timothy McVeigh', c: 'militant', y: 'Oklahoma City bombing, 1995', l: 'Anti-government militia movement', conf: 'medium',
    v: [50, -90, 30, 50, -10, 40, -60, null, null, 100],
    note: 'Gulf War veteran radicalized by Ruby Ridge and Waco; bombed a federal building, killing 168. Gun-rights absolutist influenced by "The Turner Diaries."' },
  { n: 'Anders Breivik', c: 'militant', y: 'Norway attacks, 2011', l: 'Counter-jihad ethnonationalism', conf: 'high',
    v: [30, 60, 90, 90, 40, 100, 80, 80, null, 100],
    note: 'Murdered 77 people, mostly teenagers at a Labour Party youth camp. His manifesto attacks "cultural Marxism," Islam and multiculturalism and calls for cultural Christianity.' },
  { n: 'Joseph Kony', c: 'militant', y: 'Lord\'s Resistance Army, 1987–', l: 'Millenarian Christian militancy', conf: 'low',
    v: [null, 100, null, null, 90, null, 100, 100, null, 100],
    note: 'Claims to channel spirits and to fight for rule by the Ten Commandments. Abducted tens of thousands of children as soldiers and sex slaves. Little coherent program beyond that.' },

  // ---- Dictators and heads of state ----
  { n: 'Vladimir Lenin', c: 'ruler', y: 'Soviet Russia, 1917–1924', l: 'Marxism-Leninism', conf: 'high',
    v: [-95, 85, -50, -80, -100, -30, 60, 80, 60, 100],
    note: 'Led the October Revolution; founded the one-party state and the Cheka. Legalized abortion and divorce early on. Expected world revolution.' },
  { n: 'Joseph Stalin', c: 'ruler', y: 'USSR, 1924–1953', l: 'Marxism-Leninism (Stalinism)', conf: 'high',
    v: [-100, 100, 30, 60, -100, 60, 80, 100, 90, 90],
    note: 'Forced collectivization, the Great Terror, the Gulag, deportation of whole nationalities. Reversed early Soviet social liberalism; "socialism in one country."' },
  { n: 'Mao Zedong', c: 'ruler', y: 'PRC, 1949–1976', l: 'Maoism', conf: 'high',
    v: [-100, 100, -40, 40, -100, 30, 70, 90, 90, 100],
    note: 'Great Leap Forward famine, the Cultural Revolution against "the Four Olds." "Political power grows out of the barrel of a gun."' },
  { n: 'Pol Pot', c: 'ruler', y: 'Khmer Rouge, 1975–1979', l: 'Agrarian Maoism', conf: 'high',
    v: [-100, 100, -20, 100, -100, 90, 80, 100, -60, 100],
    note: 'Emptied the cities, abolished money and religion, killed roughly a quarter of Cambodia\'s population. Targeted Vietnamese, Cham and Chinese minorities.' },
  { n: 'Adolf Hitler', c: 'ruler', y: 'Germany, 1933–1945', l: 'National Socialism', conf: 'high',
    v: [0, 100, 70, 100, 10, 100, 100, 100, 30, 90],
    note: 'Totalitarian racial state, the Holocaust, wars of conquest. Private property kept under heavy state direction.' },
  { n: 'Benito Mussolini', c: 'ruler', y: 'Italy, 1922–1943', l: 'Fascism', conf: 'high',
    v: [10, 95, 60, 100, 20, 70, 95, 90, 60, 80],
    note: 'Coined "fascism," took power after the March on Rome, built the corporatist one-party state, invaded Ethiopia. Racial laws from 1938.' },
  { n: 'Francisco Franco', c: 'ruler', y: 'Spain, 1939–1975', l: 'National Catholicism', conf: 'high',
    v: [20, 90, 90, 90, 90, 60, 60, 95, null, 80],
    note: 'Won the Civil War after a military coup; Catholic Church restored as state religion, regional languages suppressed. Market liberalization from 1959.' },
  { n: 'Augusto Pinochet', c: 'ruler', y: 'Chile, 1973–1990', l: 'Authoritarian free-market conservatism', conf: 'high',
    v: [80, 90, 70, 70, 40, 30, 60, 95, null, 80],
    note: 'Seized power in a coup; the "Chicago Boys" privatization program; thousands killed or disappeared. Stepped down after losing the 1988 plebiscite.' },
  { n: 'Fidel Castro', c: 'ruler', y: 'Cuba, 1959–2008', l: 'Marxism-Leninism', conf: 'high',
    v: [-90, 90, -10, 50, -70, -10, 60, 80, 40, 100],
    note: 'Took power by guerrilla war; nationalized the economy, one-party rule, sent troops to Angola. Persecuted gay men in the UMAP camps, later apologized.' },
  { n: 'Che Guevara', c: 'ruler', y: 'Cuba, 1959–1965', l: 'Guevarism (guerrilla Marxism)', conf: 'high',
    v: [-95, 80, -30, -60, -80, -10, 90, 90, null, 100],
    note: 'Argentine revolutionary who oversaw executions at La Cabaña and pushed rapid nationalization. Called for "two, three, many Vietnams." Killed in Bolivia trying to export the revolution.' },
  { n: 'Ruhollah Khomeini', c: 'ruler', y: 'Iran, 1979–1989', l: 'Khomeinism', conf: 'high',
    v: [-30, 90, 95, 60, 100, 70, 70, 95, null, 90],
    note: 'Led the Islamic Revolution, created rule of the jurist, the fatwa against Salman Rushdie, mass executions of prisoners in 1988.' },
  { n: 'Kim Jong Un', c: 'ruler', y: 'North Korea, 2011–', l: 'Juche', conf: 'high',
    v: [-80, 100, 50, 100, -60, 80, 90, 100, 70, null],
    note: 'Third hereditary leader; nuclear and missile program, executions of his uncle and others, total control of information.' },
  { n: 'Vladimir Putin', c: 'ruler', y: 'Russia, 1999–', l: 'Authoritarian national conservatism', conf: 'high',
    v: [30, 85, 70, 90, 50, 40, 85, 80, 80, 20],
    note: 'Invaded Ukraine in 2014 and 2022, "gay propaganda" laws, alliance with the Orthodox Church, oil-and-gas state economy, jailed and killed opponents.' },
  { n: 'Xi Jinping', c: 'ruler', y: 'China, 2012–', l: 'Marxism-Leninism with Chinese characteristics', conf: 'high',
    v: [-40, 95, 30, 70, -80, 50, 50, 80, 30, -30],
    note: 'Ended term limits, mass internment of Uyghurs, "common prosperity," tightened control of private firms. Promotes "ecological civilization" while expanding coal.' },
  { n: 'Lee Kuan Yew', c: 'ruler', y: 'Singapore, 1959–1990', l: 'Authoritarian developmentalism', conf: 'high',
    v: [50, 80, 50, 40, -30, -20, 30, 90, 40, -30],
    note: 'Built Singapore into a trade hub; caning and the death penalty for drug trafficking, press controls, enforced ethnic quotas in public housing.' },
  { n: 'Margaret Thatcher', c: 'ruler', y: 'UK, 1979–1990', l: 'Thatcherism (neoliberal conservatism)', conf: 'high',
    v: [80, 40, 50, 50, 30, 10, 60, 70, 40, -80],
    note: 'Privatization, broke the miners\' union, Falklands War, Section 28. Early to warn about climate change in 1989, before turning skeptical of the politics around it.' },

  // ---- Politicians and activists ----
  { n: 'Mahatma Gandhi', c: 'activist', y: 'Indian independence, 1915–1948', l: 'Gandhian nonviolence', conf: 'high',
    v: [-50, -70, 40, 60, 70, -60, -100, -60, -90, 20],
    note: 'Mass civil disobedience against British rule, village self-sufficiency, opposed industrialization. Defended Muslim-Hindu unity. Extra-legal but strictly nonviolent.' },
  { n: 'Martin Luther King Jr.', c: 'activist', y: 'Civil rights, 1955–1968', l: 'Christian democratic socialism', conf: 'high',
    v: [-60, -30, 0, -40, 60, -90, -90, -50, null, 0],
    note: 'Baptist minister who led nonviolent civil disobedience against segregation. Opposed the Vietnam War; launched the Poor People\'s Campaign for economic justice.' },
  { n: 'Malcolm X', c: 'activist', y: 'Nation of Islam and after, 1952–1965', l: 'Black nationalism', conf: 'medium',
    v: [-40, 10, 30, 50, 80, 40, 20, null, null, 60],
    note: 'Preached Black separatism and self-defense "by any means necessary" with the Nation of Islam; after Mecca in 1964 moved toward Sunni Islam and broader human-rights framing.' },
  { n: 'Bernie Sanders', c: 'activist', y: 'US Senator, 2007–', l: 'Democratic socialism', conf: 'high',
    v: [-80, -10, -50, -10, -30, -50, -50, -50, -80, -60],
    note: 'Medicare for All, free public college, Green New Deal. Opposed the Iraq War and, early on, some free trade deals.' },
  { n: 'Ron Paul', c: 'activist', y: 'US Representative, 1976–2013', l: 'Paleolibertarianism', conf: 'high',
    v: [90, -80, 40, 50, 40, 10, -90, -30, 40, -50],
    note: 'Abolish the Fed and the income tax, end the drug war, bring troops home. Personally pro-life; opposed birthright citizenship for children of undocumented immigrants.' },

  // ---- Celebrities and notorious figures ----
  { n: 'Sean "Diddy" Combs', c: 'public', y: 'Music mogul', l: 'Democratic-aligned Black economic empowerment', conf: 'low',
    v: [20, null, -20, null, null, -40, null, null, null, -20],
    note: 'Ran the "Vote or Die" turnout campaign in 2004; endorsed Obama and Biden, then said in 2020 that Black votes "aren\'t free" and must be earned with policy. Built a business brand around Black ownership. Convicted in 2025 on federal Mann Act charges; acquitted of racketeering and sex trafficking. Little stated policy beyond this, so most axes are blank.' },
  { n: 'Jeffrey Epstein', c: 'public', y: 'Financier', l: 'No stated ideology (donor to both parties)', conf: 'low',
    v: [40, null, null, -30, null, null, null, null, null, null],
    note: 'Donated mainly to Democrats and occasionally Republicans; cultivated politicians of both parties and foreign leaders. Ran his money through US Virgin Islands tax structures. The New York Times reported he talked of seeding the human race with his DNA. Pleaded guilty in 2008 to Florida charges including procuring a minor for prostitution; died in jail in 2019 awaiting trial on federal sex-trafficking charges. Too little record for an overall match.' },
  { n: 'Kanye West (Ye)', c: 'public', y: 'Musician', l: 'Erratic religious conservatism', conf: 'low',
    v: [30, null, 60, 40, 70, 60, null, null, null, null],
    note: 'Backed Trump, ran for president in 2020 on a Christian platform opposing abortion; repeated antisemitic statements from 2022 onward. Positions shift often.' },
  { n: 'Elon Musk', c: 'public', y: 'Businessman', l: 'Tech-right populism', conf: 'medium',
    v: [50, 20, 30, 40, -10, 40, 0, 60, 10, 0],
    note: 'Moved from Obama-era donor to Trump\'s largest 2024 backer and head of DOGE federal cost cutting. Backs Germany\'s AfD; frames speech moderation as censorship. Built his fortune on electric cars and solar while opposing EV subsidies.' },
  { n: 'Joe Rogan', c: 'public', y: 'Podcaster', l: 'Heterodox libertarian-leaning', conf: 'low',
    v: [0, -60, 0, 20, -30, -10, -40, 10, null, -30],
    note: 'Endorsed Bernie Sanders in 2020 and Trump in 2024. Favors drug legalization and gun rights; opposed COVID mandates and transgender women competing in women's sports.' },
  { n: 'Andrew Tate', c: 'public', y: 'Influencer', l: 'Reactionary "manosphere" traditionalism', conf: 'low',
    v: [60, 30, 90, 40, 60, 20, null, 80, null, 30],
    note: 'Promotes male dominance and traditional gender roles; converted to Islam in 2022. Calls the global system "the Matrix." Faces rape and human-trafficking charges in Romania and the UK, which he denies.' }
];
