// Reference profiles for real ideologies.
// Vector order: econ, power, culture, nation, faith, belong, war, justice, ecology, method.
// null = the ideology has no characteristic position on that axis, so it is ignored when matching.
// These are idealized centers, not the views of every adherent.
const IDEOLOGIES = [
  { name: 'Anarcho-Communism', v: [-95, -95, -70, -80, -70, -80, -50, -80, -40, 70],
    d: 'Abolition of both the state and private property in favor of voluntary communes distributing according to need. Kropotkin, Goldman.' },
  { name: 'Anarcho-Syndicalism', v: [-85, -85, -50, -70, -50, -70, -40, -60, null, 55],
    d: 'Stateless society run through federated labor unions, reached by general strike. CNT in Spain, Rudolf Rocker.' },
  { name: 'Anarcho-Capitalism', v: [95, -95, null, -30, null, -20, -60, -20, 60, 0],
    d: 'All services, courts and security included, provided by private markets; the state is abolished. Murray Rothbard, David Friedman.' },
  { name: 'Anarcho-Primitivism', v: [-40, -80, null, null, null, null, -40, null, -100, 80],
    d: 'Rejects industrial and agricultural civilization itself as the root of domination. John Zerzan.' },
  { name: 'Libertarian Socialism', v: [-75, -70, -60, -50, -60, -70, -50, -60, -40, 10],
    d: 'Social ownership through decentralized, democratic, non-state institutions. Chomsky, council communism.' },
  { name: 'Democratic Confederalism', v: [-70, -60, -80, -50, -50, -50, 0, -50, -80, 30],
    d: 'Stateless self-government through local assemblies, with gender equality and ecology at its core. Developed by Abdullah Öcalan from Murray Bookchin.' },
  { name: 'Marxism-Leninism', v: [-95, 80, -20, -20, -90, -30, 40, 60, 60, 85],
    d: 'One-party vanguard state, central planning and state atheism on the road to communism. USSR, Warsaw Pact.' },
  { name: 'Maoism', v: [-100, 85, -40, 10, -95, -20, 50, 60, 40, 95],
    d: 'Marxism-Leninism adapted to peasant revolution, protracted people\'s war and continuous revolution.' },
  { name: 'Trotskyism', v: [-95, 40, -50, -90, -80, -60, 20, null, null, 80],
    d: 'Permanent, international revolution led by workers; opposes Stalinist bureaucracy.' },
  { name: 'Juche', v: [-85, 100, 40, 100, -60, 80, 85, 100, 60, null],
    d: 'North Korean state doctrine: self-reliance, military-first politics and a hereditary supreme leader.' },
  { name: 'Revolutionary Socialist Nationalism', v: [-85, 70, -10, 70, -60, 0, 50, 50, 40, 90],
    d: 'National liberation through armed struggle combined with a Marxist economic program. Cuban revolution, PFLP, many anti-colonial movements.' },
  { name: 'Militant Separatism', v: [-30, 75, -10, 95, -20, 50, 80, 60, null, 95],
    d: 'An armed movement for an independent homeland for one people, where the national cause overrides other commitments. LTTE, ETA, early PKK.' },
  { name: 'Democratic Socialism', v: [-70, -20, -60, -40, -50, -60, -40, -60, -50, -60],
    d: 'Social ownership of major industry achieved through democratic means and civil liberties.' },
  { name: 'Social Democracy', v: [-45, 0, -40, -30, -40, -50, -20, -40, -40, -80],
    d: 'Regulated market economy with a large welfare state and strong unions. The Nordic model.' },
  { name: 'Eco-Socialism', v: [-75, -20, -60, -50, -50, -60, -60, -50, -90, 0],
    d: 'Holds that capitalism drives ecological collapse and must be replaced by planned, democratic production.' },
  { name: 'Green Politics', v: [-40, -30, -60, -50, -50, -60, -70, -50, -90, -60],
    d: 'Ecology, nonviolence, grassroots democracy and social justice as its four pillars.' },
  { name: 'Left-Wing Populism', v: [-60, 20, -20, 30, -20, -30, -30, -20, -20, 10],
    d: 'The people against an economic elite; redistribution, sovereignty and anti-establishment politics. Podemos, Chávez in his early years.' },
  { name: 'Progressivism', v: [-50, 0, -75, -40, -60, -70, -30, -50, -60, -50],
    d: 'Active government to reduce inequality and expand civil rights, with strong social liberalism.' },
  { name: 'Social Liberalism', v: [-20, -20, -50, -40, -50, -60, -10, -30, -30, -80],
    d: 'Individual liberty plus a welfare state to make that liberty real. Mainstream center-left.' },
  { name: 'Liberal Internationalism', v: [-10, 10, -20, -80, -20, -30, 45, 10, null, -80],
    d: 'Spreading liberal democracy through international institutions, and by force when necessary. Wilson, post-1945 Atlantic order.' },
  { name: 'Technocracy', v: [-10, 40, -30, -50, -70, -30, null, null, null, -40],
    d: 'Government by technical experts optimizing outcomes, with democratic contest downplayed.' },
  { name: 'Centrism', v: [0, 0, 0, 0, 0, 0, 0, 0, 0, -70],
    d: 'Rejects the far ends of most axes; prefers compromise and incremental change.' },
  { name: 'Georgism', v: [20, -30, null, -30, -30, -40, -30, null, -20, -60],
    d: 'Free markets funded by a single tax on land value. Henry George.' },
  { name: 'Neoliberalism', v: [55, 0, -30, -60, -40, -50, 20, 0, 30, -80],
    d: 'Privatization, deregulation, free trade and sound money within a liberal-democratic order. Washington Consensus.' },
  { name: 'Classical Liberalism', v: [70, -50, -10, -30, -40, -40, -20, -10, 30, -60],
    d: 'Limited government, rule of law, free markets and individual rights. Locke, Smith, Mill.' },
  { name: 'Minarchist Libertarianism', v: [85, -75, -20, -20, -30, -40, -50, -30, 40, -40],
    d: 'The state limited to courts, police and defense; maximal economic and personal freedom.' },
  { name: 'Paleolibertarianism', v: [85, -70, 50, 40, 30, 30, -50, 20, 50, -20],
    d: 'Free-market libertarianism combined with cultural traditionalism and hostility to immigration. Ron Paul\'s circle, Hans-Hermann Hoppe.' },
  { name: 'Liberal Conservatism', v: [45, 10, 30, 10, 10, -10, 30, 40, 30, -80],
    d: 'Free markets and moderate social conservatism within liberal institutions. The postwar center-right.' },
  { name: 'Christian Democracy', v: [-10, 15, 45, -20, 55, -20, 0, 20, -20, -80],
    d: 'Social market economy guided by Catholic social teaching; family, subsidiarity and European integration.' },
  { name: 'Hamiltonian Federalism', v: [40, 40, 20, 60, 0, null, 20, 40, 80, -70],
    d: 'A strong national government that builds finance, industry and infrastructure behind tariffs. Hamilton, Henry Clay\'s American System.' },
  { name: 'Jeffersonian Agrarianism', v: [40, -60, 40, 30, -40, null, -40, null, -10, -10],
    d: 'Small government, states\' rights, independent farmers and suspicion of banks and standing armies.' },
  { name: 'Jacksonian Populism', v: [30, 20, 40, 70, 10, 60, 50, 60, 60, 0],
    d: 'The common man against eastern elites, expansion westward, hard money and a strong presidency.' },
  { name: 'Neoconservatism', v: [50, 40, 40, 30, 30, -10, 85, 60, 40, -70],
    d: 'Muscular promotion of democracy and American power abroad combined with free markets.' },
  { name: 'National Conservatism', v: [10, 45, 70, 75, 50, 40, 20, 65, 30, -40],
    d: 'Nation, family and religion as the foundations of politics; skeptical of free trade and global institutions. Orbán, the NatCon movement.' },
  { name: 'Paleoconservatism', v: [30, 20, 75, 75, 55, 50, -40, 60, 30, -40],
    d: 'Tradition, localism, restricted immigration and non-intervention. Pat Buchanan, Russell Kirk.' },
  { name: 'Right-Wing Populism', v: [10, 50, 55, 80, 40, 55, 0, 70, 50, 0],
    d: 'The people against elites and outsiders; restrictionist immigration, protectionism and a strong leader.' },
  { name: 'Christian Nationalism', v: [30, 50, 85, 75, 85, 50, 30, 70, 40, 10],
    d: 'The nation as a Christian nation whose laws and identity should reflect that faith.' },
  { name: 'Catholic Integralism', v: [-10, 60, 90, 20, 95, 30, null, 50, null, 0],
    d: 'Temporal power subordinated to the spiritual authority of the Church. Pre-Vatican II political theology.' },
  { name: 'Reactionary Monarchism', v: [20, 85, 95, 60, 70, 40, 30, 80, null, 10],
    d: 'Restoration of hereditary monarchy and hierarchy against the legacy of 1789. De Maistre.' },
  { name: 'National Catholicism', v: [20, 90, 90, 90, 90, 60, 60, 95, null, 70],
    d: 'Authoritarian nationalism fused with the Catholic Church, which regains control of education and morals. Franco\'s Spain, Salazar\'s Portugal.' },
  { name: 'Authoritarian Capitalism', v: [70, 80, 40, 40, null, null, 30, 85, 60, -10],
    d: 'Market economics under a regime that suppresses political freedom. Pinochet\'s Chile, Lee Kuan Yew\'s Singapore.' },
  { name: 'Islamism', v: [-10, 50, 85, -10, 90, 40, 20, 70, null, 10],
    d: 'Sharia as the basis of law, pursued mostly through parties, preaching and social services. Muslim Brotherhood.' },
  { name: 'Khomeinism', v: [-20, 85, 90, 60, 100, 70, 60, 90, null, 60],
    d: 'Velayat-e faqih: rule by the senior Shia jurist, exported revolution and resistance to the West. Islamic Republic of Iran, Hezbollah.' },
  { name: 'Salafi-Jihadism', v: [null, 95, 100, null, 100, 95, 95, 100, null, 100],
    d: 'Armed jihad to overthrow existing states and restore a caliphate under a literalist reading of sharia. al-Qaeda, ISIS. Rejects the nation-state itself, so the sovereignty axis is not used.' },
  { name: 'Ethnonationalism', v: [null, 50, 70, 95, null, 100, null, 70, null, 40],
    d: 'The nation defined by ancestry, with citizenship and belonging to match. White nationalism belongs here.' },
  { name: 'Fascism', v: [10, 95, 60, 100, 20, 70, 90, 90, 60, 70],
    d: 'Totalitarian national rebirth through a single party, corporatism, militarism and the cult of a leader. Mussolini.' },
  { name: 'National Socialism', v: [-10, 100, 70, 100, 10, 100, 100, 95, 40, 80],
    d: 'Fascism organized around biological racism, antisemitism and conquest. Hitler.' },
  { name: 'Apocalyptic Millenarianism', v: [null, 90, null, null, 100, 50, 80, null, null, 100],
    d: 'A movement organized around an imminent end of the world that its members may try to bring about. Aum Shinrikyo.' },
  { name: 'Distributism', v: [-20, 0, 60, 20, 60, 0, -20, null, -30, -40],
    d: 'Widespread small ownership instead of either capitalism or socialism. Chesterton, Belloc.' }
];
