// Reference profiles for real ideologies.
// Vector order: econ, power, culture, nation, faith, belong, war, justice, ecology, method, pop.
// pop (populism) follows Mudde's definitions: high where the ideology is built on a people-versus-elite
// frame, low where it relies on representation, expertise or hierarchy, null where it varies.
// null = the ideology has no characteristic position on that axis, so it is ignored when matching.
// These are idealized centers, not the views of every adherent. src names the definitional source each profile follows.
// Populism is treated as a thin ideology (Mudde 2004): it is not a position on these axes, so there is no
// stand-alone "populism" profile, only host ideologies that are commonly populist.
const IDEOLOGIES = [
  { name: 'Anarcho-Communism', v: [-95, -95, -70, -80, -70, -80, -50, -80, -40, 70, null],
    d: 'Abolition of both the state and private property in favor of voluntary communes distributing according to need. Kropotkin, Goldman.',
    src: 'Kropotkin, The Conquest of Bread (1892)' },
  { name: 'Anarcho-Syndicalism', v: [-85, -85, -50, -70, -50, -70, -40, -60, null, 55, null],
    d: 'Stateless society run through federated labor unions, reached by general strike. CNT in Spain, Rudolf Rocker.',
    src: 'Rocker, Anarcho-Syndicalism (1938)' },
  { name: 'Anarcho-Capitalism', v: [95, -95, null, -30, null, -20, -60, -20, 60, 0, -20],
    d: 'All services, courts and security included, provided by private markets; the state is abolished. Murray Rothbard, David Friedman.',
    src: 'Rothbard, For a New Liberty (1973)' },
  { name: 'Anarcho-Primitivism', v: [-40, -80, null, null, null, null, -40, null, -100, 80, null],
    d: 'Rejects industrial and agricultural civilization itself as the root of domination. John Zerzan.',
    src: 'Zerzan, Future Primitive (1994)' },
  { name: 'Libertarian Socialism', v: [-75, -70, -60, -50, -60, -70, -50, -60, -40, 10, null],
    d: 'Social ownership through decentralized, democratic, non-state institutions. Chomsky, council communism.',
    src: 'Guérin, Anarchism: From Theory to Practice (1970)' },
  { name: 'Democratic Confederalism', v: [-70, -60, -80, -50, -50, -50, 0, -50, -80, 30, null],
    d: 'Stateless self-government through local assemblies, with gender equality and ecology at its core. Developed by Abdullah Öcalan from Murray Bookchin.',
    src: 'Öcalan, Democratic Confederalism (2011); Bookchin, The Ecology of Freedom (1982)' },
  { name: 'Marxism-Leninism', v: [-95, 80, -20, -20, -90, -30, 40, 60, 60, 85, -20],
    d: 'One-party vanguard state, central planning and state atheism on the road to communism. USSR, Warsaw Pact.',
    src: 'Lenin, The State and Revolution (1917); Kolakowski, Main Currents of Marxism (1978)' },
  { name: 'Maoism', v: [-100, 85, -40, 10, -95, -20, 50, 60, 40, 95, 50],
    d: 'Marxism-Leninism adapted to peasant revolution, protracted people\'s war and continuous revolution.',
    src: 'Mao, On Protracted War (1938); Schram, The Thought of Mao Tse-tung (1989)' },
  { name: 'Trotskyism', v: [-95, 40, -50, -90, -80, -60, 20, null, null, 80, null],
    d: 'Permanent, international revolution led by workers; opposes Stalinist bureaucracy.',
    src: 'Trotsky, The Permanent Revolution (1930)' },
  { name: 'Juche', v: [-85, 100, 40, 100, -60, 80, 85, 100, 60, null, null],
    d: 'North Korean state doctrine: self-reliance, military-first politics and a hereditary supreme leader.',
    src: 'Lankov, The Real North Korea (2013)' },
  { name: 'Revolutionary Socialist Nationalism', v: [-85, 70, -10, 70, -60, 0, 50, 50, 40, 90, 50],
    d: 'National liberation through armed struggle combined with a Marxist economic program. Cuban revolution, PFLP, many anti-colonial movements.',
    src: 'Rapoport (2004), anti-colonial and new-left waves' },
  { name: 'Militant Separatism', v: [-30, 75, -10, 95, -20, 50, 80, 60, null, 95, 30],
    d: 'An armed movement for an independent homeland for one people, where the national cause overrides other commitments. LTTE, ETA, early PKK.',
    src: 'Rapoport (2004), anti-colonial wave; Byman, "The Logic of Ethnic Terrorism" (1998)' },
  { name: 'Democratic Socialism', v: [-70, -20, -60, -40, -50, -60, -40, -60, -50, -60, 20],
    d: 'Social ownership of major industry achieved through democratic means and civil liberties.',
    src: 'Harrington, Socialism (1972)' },
  { name: 'Social Democracy', v: [-45, 0, -40, -30, -40, -50, -20, -40, -40, -80, -40],
    d: 'Regulated market economy with a large welfare state and strong unions. The Nordic model.',
    src: 'Berman, The Primacy of Politics (2006)' },
  { name: 'Eco-Socialism', v: [-75, -20, -60, -50, -50, -60, -60, -50, -90, 0, null],
    d: 'Holds that capitalism drives ecological collapse and must be replaced by planned, democratic production.',
    src: 'Kovel, The Enemy of Nature (2002)' },
  { name: 'Green Politics', v: [-40, -30, -60, -50, -50, -60, -70, -50, -90, -60, -30],
    d: 'Ecology, nonviolence, grassroots democracy and social justice as its four pillars.',
    src: 'Dobson, Green Political Thought (1990)' },
  { name: '21st-Century Socialism', v: [-80, 50, -20, 70, null, -20, null, null, null, 30, 90],
    d: 'State-led redistribution and nationalization under a plebiscitary executive, framed as participatory democracy and anti-imperialism. Chavismo, Evo Morales, Rafael Correa.',
    src: 'Hawkins, Venezuela\'s Chavismo and Populism in Comparative Perspective (2010)' },
  { name: 'Progressivism', v: [-50, 0, -75, -40, -60, -70, -30, -50, -60, -50, 0],
    d: 'Active government to reduce inequality and expand civil rights, with strong social liberalism.',
    src: 'Freeden, Ideologies and Political Theory (1996)' },
  { name: 'Social Liberalism', v: [-20, -20, -50, -40, -50, -60, -10, -30, -30, -80, -60],
    d: 'Individual liberty plus a welfare state to make that liberty real. Mainstream center-left.',
    src: 'Hobhouse, Liberalism (1911); Rawls, A Theory of Justice (1971)' },
  { name: 'Liberal Internationalism', v: [-10, 10, -20, -80, -20, -30, 45, 10, null, -80, -70],
    d: 'Spreading liberal democracy through international institutions, and by force when necessary. Wilson, post-1945 Atlantic order.',
    src: 'Ikenberry, Liberal Leviathan (2011)' },
  { name: 'Centrism', v: [0, 0, 0, 0, 0, 0, 0, 0, 0, -70, -60],
    d: 'Rejects the far ends of most axes; prefers compromise and incremental change.' },
  { name: 'Georgism', v: [20, -30, null, -30, -30, -40, -30, null, -20, -60, null],
    d: 'Free markets funded by a single tax on land value. Henry George.',
    src: 'George, Progress and Poverty (1879)' },
  { name: 'Neoliberalism', v: [55, 0, -30, -60, -40, -50, 20, 0, 30, -80, -70],
    d: 'Privatization, deregulation, free trade and sound money within a liberal-democratic order. Washington Consensus.',
    src: 'Harvey, A Brief History of Neoliberalism (2005); Slobodian, Globalists (2018)' },
  { name: 'Classical Liberalism', v: [70, -50, -10, -30, -40, -40, -20, -10, 30, -60, -50],
    d: 'Limited government, rule of law, free markets and individual rights. Locke, Smith, Mill.',
    src: 'Locke, Second Treatise (1689); Smith, Wealth of Nations (1776)' },
  { name: 'Minarchist Libertarianism', v: [85, -75, -20, -20, -30, -40, -50, -30, 40, -40, -20],
    d: 'The state limited to courts, police and defense; maximal economic and personal freedom.',
    src: 'Nozick, Anarchy, State, and Utopia (1974)' },
  { name: 'Paleolibertarianism', v: [85, -70, 50, 40, 30, 30, -50, 20, 50, -20, 30],
    d: 'Free-market libertarianism combined with cultural traditionalism and hostility to immigration. Ron Paul\'s circle, Hans-Hermann Hoppe.',
    src: 'Rockwell, "The Case for Paleo-libertarianism" (1990)' },
  { name: 'Liberal Conservatism', v: [45, 10, 30, 10, 10, -10, 30, 40, 30, -80, -50],
    d: 'Free markets and moderate social conservatism within liberal institutions. The postwar center-right.',
    src: 'Freeden (1996); Oakeshott, Rationalism in Politics (1962)' },
  { name: 'Christian Democracy', v: [-10, 15, 45, -20, 55, -20, 0, 20, -20, -80, -50],
    d: 'Social market economy guided by Catholic social teaching; family, subsidiarity and European integration.',
    src: 'Kalyvas & van Kersbergen (2010), "Christian Democracy," Annual Review of Political Science' },
  { name: 'Hamiltonian Federalism', v: [40, 40, 20, 60, 0, null, 20, 40, 80, -70, -50],
    d: 'A strong national government that builds finance, industry and infrastructure behind tariffs. Hamilton, Henry Clay\'s American System.',
    src: 'Mead, Special Providence (2001)' },
  { name: 'Jeffersonian Agrarianism', v: [40, -60, 40, 30, -40, null, -40, null, -10, -10, 30],
    d: 'Small government, states\' rights, independent farmers and suspicion of banks and standing armies.',
    src: 'Mead, Special Providence (2001)' },
  { name: 'Jacksonian Populism', v: [30, 20, 40, 70, 10, 60, 50, 60, 60, 0, 70],
    d: 'The common man against eastern elites, expansion westward, hard money and a strong presidency.',
    src: 'Mead, Special Providence (2001)' },
  { name: 'Neoconservatism', v: [50, 40, 40, 30, 30, -10, 85, 60, 40, -70, -40],
    d: 'Muscular promotion of democracy and American power abroad combined with free markets.',
    src: 'Kristol, Neoconservatism: The Autobiography of an Idea (1995)' },
  { name: 'National Conservatism', v: [10, 45, 70, 75, 50, 40, 20, 65, 30, -40, 30],
    d: 'Nation, family and religion as the foundations of politics; skeptical of free trade and global institutions. Orbán, the NatCon movement.',
    src: 'Hazony, The Virtue of Nationalism (2018)' },
  { name: 'Paleoconservatism', v: [30, 20, 75, 75, 55, 50, -40, 60, 30, -40, 40],
    d: 'Tradition, localism, restricted immigration and non-intervention. Pat Buchanan, Russell Kirk.',
    src: 'Kirk, The Conservative Mind (1953); Buchanan, A Republic, Not an Empire (1999)' },
  { name: 'Populist Radical Right', v: [null, 60, 60, 80, null, 80, null, 70, null, 10, 90],
    d: 'Nativism, authoritarianism and populism, with economic policy secondary and variable. Le Pen\'s National Rally, the FPÖ, the AfD.',
    src: 'Mudde, Populist Radical Right Parties in Europe (2007)' },
  { name: 'Christian Nationalism', v: [30, 50, 85, 75, 85, 50, 30, 70, 40, 10, 40],
    d: 'The nation as a Christian nation whose laws and identity should reflect that faith.',
    src: 'Whitehead & Perry, Taking America Back for God (2020)' },
  { name: 'Catholic Integralism', v: [-10, 60, 90, 20, 95, 30, null, 50, null, 0, -40],
    d: 'Temporal power subordinated to the spiritual authority of the Church. Pre-Vatican II political theology.',
    src: 'Pink (2020), "In Defence of Catholic Integralism"; Leo XIII, Immortale Dei (1885)' },
  { name: 'Reactionary Monarchism', v: [20, 85, 95, 60, 70, 40, 30, 80, null, 10, -60],
    d: 'Restoration of hereditary monarchy and hierarchy against the legacy of 1789. De Maistre.',
    src: 'de Maistre, Considerations on France (1797)' },
  { name: 'National Catholicism', v: [20, 90, 90, 90, 90, 60, 60, 95, null, 70, -20],
    d: 'Authoritarian nationalism fused with the Catholic Church, which regains control of education and morals. Franco\'s Spain, Salazar\'s Portugal.',
    src: 'Payne, Franco and Hitler (2008); Preston, Franco (1993)' },
  { name: 'Authoritarian Capitalism', v: [70, 80, 40, 40, null, null, 30, 85, 60, -10, -50],
    d: 'Market economics under a regime that suppresses political freedom. Pinochet\'s Chile, Lee Kuan Yew\'s Singapore.',
    src: 'Linz, Totalitarian and Authoritarian Regimes (2000)' },
  { name: 'Islamism', v: [-10, 50, 85, -10, 90, 40, 20, 70, null, 10, 20],
    d: 'Sharia as the basis of law, pursued mostly through parties, preaching and social services. Muslim Brotherhood.',
    src: 'Roy, The Failure of Political Islam (1994); Mandaville, Islam and Politics (2014)' },
  { name: 'Khomeinism', v: [-20, 85, 90, 60, 100, 70, 60, 90, null, 60, 40],
    d: 'Velayat-e faqih: rule by the senior Shia jurist, exported revolution and resistance to the West. Islamic Republic of Iran, Hezbollah.',
    src: 'Abrahamian, Khomeinism (1993)' },
  { name: 'Salafi-Jihadism', v: [null, 90, 100, null, 100, 85, 95, 95, null, 100, null],
    d: 'Armed jihad against the "far enemy" (the West) and the regimes it backs, aiming at a future caliphate under a literalist reading of sharia. al-Qaeda. Rejects the nation-state itself, so the sovereignty axis is not used.',
    src: 'Wiktorowicz (2006), "Anatomy of the Salafi Movement"; Hegghammer, Jihad in Saudi Arabia (2010)' },
  { name: 'Takfiri Jihadism', v: [null, 100, 100, null, 100, 100, 100, 100, null, 100, null],
    d: 'The Salafi-jihadist current that declares other Muslims, Shia above all, apostates to be killed, and builds a caliphate now rather than later. ISIS, al-Qaeda in Iraq under Zarqawi.',
    src: 'Bunzel (2015), From Paper State to Caliphate; Wiktorowicz (2006)' },
  { name: 'Ethnonationalism', v: [null, 50, 70, 95, null, 100, null, 70, null, 40, 40],
    d: 'The nation defined by ancestry, with citizenship and belonging to match. White nationalism belongs here.',
    src: 'Connor, Ethnonationalism (1994)' },
  { name: 'Fascism', v: [10, 95, 60, 100, 20, 70, 90, 90, 60, 70, 50],
    d: 'Totalitarian national rebirth through a single party, corporatism, militarism and the cult of a leader. Mussolini.',
    src: 'Griffin, The Nature of Fascism (1991); Paxton, The Anatomy of Fascism (2004)' },
  { name: 'National Socialism', v: [-10, 100, 70, 100, 10, 100, 100, 95, 40, 80, 50],
    d: 'Fascism organized around biological racism, antisemitism and conquest. Hitler.',
    src: 'Kershaw, Hitler (1998–2000); Paxton (2004)' },
  { name: 'Apocalyptic Millenarianism', v: [null, 90, null, null, 100, 50, 80, null, null, 100, null],
    d: 'A movement organized around an imminent end of the world that its members may try to bring about. Aum Shinrikyo.',
    src: 'Lifton, Destroying the World to Save It (1999)' },
  { name: 'Distributism', v: [-20, 0, 60, 20, 60, 0, -20, null, -30, -40, null],
    d: 'Widespread small ownership instead of either capitalism or socialism. Chesterton, Belloc.',
    src: 'Belloc, The Servile State (1912); Chesterton, The Outline of Sanity (1926)' }
];
