// Philosopher profiles. Vector order: nat, know, real, moral, ethic, scope, will, self, pmethod.
// Scores come from each philosopher's own works, read with a standard secondary source where readings
// differ. null = no position in the works, or one too contested to score. conf: how settled the reading is.
// src: the works the scores rest on.
const PHILOSOPHERS = [
  // Ancient
  { n: 'Socrates', y: 'c. 470–399 BCE', l: 'Platonism (early)', conf: 'medium',
    v: [40, 50, -50, -80, 60, -20, null, -50, -30],
    note: 'Known only through Plato, Xenophon and Aristophanes; this follows Plato\'s early dialogues. Virtue is knowledge, no one does wrong willingly, and one must never do wrong even in return. The soul matters more than the body.',
    src: ['Plato, Apology, Crito, Euthyphro, Gorgias', 'Vlastos, Socrates: Ironist and Moral Philosopher (1991)'] },
  { n: 'Plato', y: 'c. 428–348 BCE', l: 'Platonism', conf: 'high',
    v: [80, 90, -80, -90, null, 20, null, -90, -20],
    note: 'The Forms are the true objects of knowledge; the soul is immortal and tripartite; justice is each part doing its own work, in the soul and the city.',
    src: ['Republic', 'Phaedo', 'Meno', 'Symposium'] },
  { n: 'Aristotle', y: '384–322 BCE', l: 'Aristotelianism', conf: 'high',
    v: [10, -20, -80, -70, null, 70, 30, -60, -40],
    note: 'Form in matter, not apart; knowledge rises from perception; the good life is virtuous activity in a political community; the soul is the form of a living body.',
    src: ['Nicomachean Ethics', 'Metaphysics', 'De Anima', 'Politics'] },
  { n: 'Epicurus', y: '341–270 BCE', l: 'Epicureanism', conf: 'high',
    v: [-80, -70, -70, -30, -50, 40, 40, 30, -30],
    note: 'Atoms and void; death is nothing to us; pleasure, understood as freedom from pain and fear, is the goal; the swerve of atoms leaves room for freedom.',
    src: ['Letter to Menoeceus', 'Principal Doctrines', 'Lucretius, De Rerum Natura'] },
  { n: 'Epictetus', y: 'c. 50–135', l: 'Stoicism', conf: 'high',
    v: [40, null, -60, -80, 40, -60, 0, -30, null],
    note: 'Former slave whose core teaching is the division between what is up to us (our judgments and choices) and what is not. Virtue is the only good; all humans are kin through shared reason.',
    src: ['Discourses', 'Handbook (Enchiridion)', 'Long, Epictetus (2002)'] },
  { n: 'Marcus Aurelius', y: '121–180', l: 'Stoicism', conf: 'high',
    v: [40, null, -60, -80, 50, -70, -30, 40, null],
    note: 'Roman emperor writing private notes to himself: accept fate, do your duty to the human community, remember that everything is in flux and soon gone.',
    src: ['Meditations', 'Hadot, The Inner Citadel (1998)'] },
  { n: 'Sextus Empiricus', y: 'c. 160–210', l: 'Pyrrhonian Skepticism', conf: 'high',
    v: [null, -30, 40, 50, null, 40, null, null, 0],
    note: 'Our main source for Pyrrhonism: oppose every argument with an equal one, suspend judgment, and live by appearances, custom and law.',
    src: ['Outlines of Pyrrhonism', 'Against the Mathematicians'] },
  { n: 'Laozi', y: 'traditionally 6th c. BCE', l: 'Daoism', conf: 'medium',
    v: [40, -40, 50, 50, null, 30, null, 60, 70],
    note: 'The Daodejing\'s author may be legendary or composite. The Dao that can be named is not the constant Dao; the sage rules by not forcing.',
    src: ['Daodejing', 'Graham, Disputers of the Tao (1989)'] },
  { n: 'Zhuangzi', y: 'c. 369–286 BCE', l: 'Daoism', conf: 'medium',
    v: [20, -50, 70, 70, null, 40, null, 80, 80],
    note: 'Playful, skeptical stories (the butterfly dream, Cook Ding) against fixed distinctions of right and wrong and for spontaneous skill.',
    src: ['Zhuangzi (Inner Chapters)', 'Graham (1989)'] },
  { n: 'Confucius', y: '551–479 BCE', l: 'Confucianism', conf: 'medium',
    v: [10, null, -40, -60, 30, 90, null, 30, 40],
    note: 'Humaneness (ren) and ritual propriety (li), cultivated through learning; filial piety; rulers should govern by virtue and example.',
    src: ['Analects', 'Ivanhoe, Confucian Moral Self Cultivation (2000)'] },
  { n: 'Mencius', y: 'c. 372–289 BCE', l: 'Confucianism', conf: 'high',
    v: [20, 40, -50, -80, 30, 70, null, -20, 30],
    note: 'Human nature is good: we have innate "sprouts" of benevolence, righteousness, propriety and wisdom that need cultivation. A ruler who loses the people\'s welfare loses Heaven\'s mandate.',
    src: ['Mencius', 'Van Norden, Virtue Ethics and Consequentialism in Early Chinese Philosophy (2007)'] },
  { n: 'Siddhartha Gautama (the Buddha)', y: 'c. 5th c. BCE', l: 'Early Buddhism', conf: 'medium',
    v: [20, -40, 30, -50, -20, -70, -20, 100, null],
    note: 'As recorded in the Pali Canon: suffering arises from craving; there is no permanent self; the eightfold path and compassion for all beings end suffering. He set aside metaphysical questions that do not lead to liberation.',
    src: ['Pali Canon (Anattalakkhana Sutta, Dhammacakkappavattana Sutta)', 'Siderits, Buddhism as Philosophy (2007)'] },
  { n: 'Nagarjuna', y: 'c. 150–250', l: 'Madhyamaka Buddhism', conf: 'medium',
    v: [10, 30, 90, -20, null, -50, null, 100, 60],
    note: 'Everything is empty of intrinsic nature, including emptiness itself; dependent origination and emptiness are the same; two truths, conventional and ultimate.',
    src: ['Mulamadhyamakakarika', 'Garfield, The Fundamental Wisdom of the Middle Way (1995)'] },
  { n: 'Adi Shankara', y: 'c. 8th c.', l: 'Advaita Vedanta', conf: 'medium',
    v: [90, 40, 40, -50, 30, -30, 0, -40, 40],
    note: 'Brahman alone is real; the world is appearance; the true Self (Atman) is identical with Brahman and liberation comes from knowing it.',
    src: ['Brahma Sutra Bhashya', 'Upadesasahasri', 'Deutsch, Advaita Vedanta (1969)'] },

  // Medieval
  { n: 'Augustine', y: '354–430', l: 'Christian Platonism', conf: 'high',
    v: [100, 50, -80, -90, 60, 20, 20, -80, 30],
    note: 'Faith seeking understanding; evil as privation of good; the restless heart finds rest only in God; free will and grace, with grace increasingly decisive in his later work.',
    src: ['Confessions', 'City of God', 'On Free Choice of the Will'] },
  { n: 'Avicenna (Ibn Sina)', y: '980–1037', l: 'Islamic Falsafa', conf: 'high',
    v: [80, 70, -80, -70, null, 0, 0, -80, -50],
    note: 'God as the Necessary Existent; the "floating man" thought experiment for an immaterial self-aware soul; the essence/existence distinction.',
    src: ['The Healing (al-Shifa)', 'Adamson, Philosophy in the Islamic World (2016)'] },
  { n: 'Al-Ghazali', y: '1058–1111', l: 'Ash\'arite theology', conf: 'high',
    v: [100, -20, -60, -80, 60, 20, -40, -70, 40],
    note: 'Attacked the philosophers in The Incoherence of the Philosophers; occasionalism (God, not fire, causes the cotton to burn); turned to Sufi experience as the path to certainty.',
    src: ['The Incoherence of the Philosophers', 'Deliverance from Error', 'Griffel, Al-Ghazali\'s Philosophical Theology (2009)'] },
  { n: 'Averroes (Ibn Rushd)', y: '1126–1198', l: 'Islamic Falsafa', conf: 'high',
    v: [70, 70, -80, -70, null, 0, null, -20, -60],
    note: 'Defended philosophy against al-Ghazali; demonstrative reason and religion cannot conflict; controversially held that there is one shared material intellect for all humans.',
    src: ['The Decisive Treatise', 'The Incoherence of the Incoherence', 'Long Commentary on De Anima'] },
  { n: 'Maimonides', y: '1138–1204', l: 'Jewish Aristotelianism', conf: 'high',
    v: [90, 60, -80, -80, 50, 30, 60, -60, -40],
    note: 'Reconciled Torah with Aristotle; negative theology (we can say only what God is not); the commandments have rational purposes.',
    src: ['The Guide for the Perplexed', 'Mishneh Torah'] },
  { n: 'Thomas Aquinas', y: '1225–1274', l: 'Thomism', conf: 'high',
    v: [90, 10, -90, -90, 60, 40, 70, -90, -40],
    note: 'Five ways to God; natural law knowable by reason; the soul as the form of the body; double effect; grace perfects nature.',
    src: ['Summa Theologiae', 'Summa contra Gentiles', 'Kenny, Aquinas (1980)'] },
  { n: 'William of Ockham', y: 'c. 1287–1347', l: 'Nominalism', conf: 'medium',
    v: [80, -50, 10, -60, 60, null, 90, -50, -60],
    note: 'Universals are only names; do not multiply entities beyond necessity; morality rests on God\'s will; strong emphasis on divine and human freedom.',
    src: ['Summa Logicae', 'Quodlibetal Questions', 'Spade, ed., Cambridge Companion to Ockham (1999)'] },

  // Early modern
  { n: 'Thomas Hobbes', y: '1588–1679', l: 'Materialist contractarianism', conf: 'high',
    v: [-70, -50, -40, 60, -20, 30, -80, 20, -40],
    note: 'Everything is matter in motion; "good" names what we desire; without a sovereign, life is solitary, poor, nasty, brutish and short; freedom is compatible with necessity.',
    src: ['Leviathan', 'Of Liberty and Necessity'] },
  { n: 'René Descartes', y: '1596–1650', l: 'Cartesian Rationalism', conf: 'high',
    v: [70, 90, -70, -50, null, null, 90, -90, -60],
    note: 'I think, therefore I am; mind and body are distinct substances; clear and distinct ideas guaranteed by God; the will is infinite in scope.',
    src: ['Meditations on First Philosophy', 'Discourse on Method', 'Principles of Philosophy'] },
  { n: 'Blaise Pascal', y: '1623–1662', l: 'Christian apologetics', conf: 'medium',
    v: [100, -30, 0, -60, null, 20, 40, -40, 60],
    note: 'The heart has its reasons which reason does not know; the wager; humanity as a thinking reed caught between greatness and misery.',
    src: ['Pensées'] },
  { n: 'Baruch Spinoza', y: '1632–1677', l: 'Rationalist monism', conf: 'high',
    v: [0, 90, -80, 40, null, -30, -100, 40, -70],
    note: 'God or Nature: one substance with infinite attributes; everything follows necessarily; good and evil are relative to us; freedom is understanding necessity. Written in geometric order.',
    src: ['Ethics', 'Theological-Political Treatise', 'Della Rocca, Spinoza (2008)'] },
  { n: 'John Locke', y: '1632–1704', l: 'Classical Empiricism', conf: 'high',
    v: [50, -80, -50, -60, 40, -30, 30, 0, -50],
    note: 'The mind begins as a blank slate; personal identity consists in continuity of consciousness; natural rights to life, liberty and property; toleration.',
    src: ['Essay Concerning Human Understanding', 'Second Treatise of Government', 'Letter Concerning Toleration'] },
  { n: 'G. W. Leibniz', y: '1646–1716', l: 'Rationalism', conf: 'high',
    v: [80, 90, 0, -70, null, -20, 30, -80, -70],
    note: 'Reality consists of monads; pre-established harmony; this is the best of all possible worlds; truths of reason versus truths of fact.',
    src: ['Monadology', 'Discourse on Metaphysics', 'Theodicy'] },
  { n: 'George Berkeley', y: '1685–1753', l: 'Idealism', conf: 'high',
    v: [90, -70, 70, -60, null, null, null, -60, -50],
    note: 'To be is to be perceived (or to perceive): there is no mind-independent matter, and God sustains the world of ideas.',
    src: ['A Treatise Concerning the Principles of Human Knowledge', 'Three Dialogues between Hylas and Philonous'] },
  { n: 'David Hume', y: '1711–1776', l: 'Classical Empiricism', conf: 'high',
    v: [-70, -90, 10, 70, -30, 20, -50, 90, -50],
    note: 'No impression of necessary connection; the self is a bundle of perceptions; reason is the slave of the passions; you cannot get an ought from an is; skeptical of miracles.',
    src: ['A Treatise of Human Nature', 'Enquiry Concerning Human Understanding', 'Dialogues Concerning Natural Religion'] },
  { n: 'Jean-Jacques Rousseau', y: '1712–1778', l: 'Social contract theory', conf: 'medium',
    v: [50, -20, null, -20, 40, 80, 60, null, 40],
    note: 'Natural goodness corrupted by society; the general will; freedom as obedience to a law one has given oneself; conscience as an inner guide.',
    src: ['The Social Contract', 'Discourse on Inequality', 'Emile'] },
  { n: 'Immanuel Kant', y: '1724–1804', l: 'Kantianism', conf: 'high',
    v: [30, 60, 40, -90, 100, -100, 80, -30, -40],
    note: 'Synthetic a priori knowledge; we know appearances, not things in themselves; the categorical imperative; God, freedom and immortality as postulates of practical reason.',
    src: ['Critique of Pure Reason', 'Groundwork of the Metaphysics of Morals', 'Critique of Practical Reason'] },

  // 19th century
  { n: 'G. W. F. Hegel', y: '1770–1831', l: 'Hegelian Idealism', conf: 'medium',
    v: [50, 70, 60, -40, 20, 60, 30, 40, 70],
    note: 'Spirit comes to know itself through history; the master-slave dialectic; freedom realized in ethical life and the rational state.',
    src: ['Phenomenology of Spirit', 'Science of Logic', 'Philosophy of Right'] },
  { n: 'Arthur Schopenhauer', y: '1788–1860', l: 'Pessimist idealism', conf: 'high',
    v: [-30, 40, 70, -10, -20, -70, -80, 70, 50],
    note: 'The world is my representation, and in itself blind will; life is suffering; compassion is the basis of morality; drew on Buddhist and Vedantic thought.',
    src: ['The World as Will and Representation', 'On the Basis of Morality'] },
  { n: 'Søren Kierkegaard', y: '1813–1855', l: 'Religious Existentialism', conf: 'high',
    v: [100, -40, 0, -40, null, 60, 100, 20, 90],
    note: 'Truth is subjectivity; the leap of faith; Abraham and the teleological suspension of the ethical; the self as a relation that relates itself to itself before God.',
    src: ['Fear and Trembling', 'Concluding Unscientific Postscript', 'The Sickness unto Death'] },
  { n: 'John Stuart Mill', y: '1806–1873', l: 'Utilitarianism', conf: 'high',
    v: [-50, -90, -60, -40, -100, -80, -40, 20, -60],
    note: 'The greatest happiness principle, with higher and lower pleasures; the harm principle; even mathematics is known from experience.',
    src: ['Utilitarianism', 'On Liberty', 'A System of Logic'] },
  { n: 'Karl Marx', y: '1818–1883', l: 'Historical Materialism', conf: 'high',
    v: [-90, -50, 10, 40, -40, -40, -60, 60, 50],
    note: 'Material conditions shape consciousness; alienated labor; religion as the opium of the people; philosophers have only interpreted the world, the point is to change it.',
    src: ['Economic and Philosophic Manuscripts of 1844', 'The German Ideology', 'Theses on Feuerbach', 'Capital'] },
  { n: 'Friedrich Nietzsche', y: '1844–1900', l: 'Nietzschean Perspectivism', conf: 'medium',
    v: [-90, -40, 70, 90, null, 70, -40, 80, 70],
    note: 'God is dead; master and slave morality; perspectivism; will to power; denied free will in the traditional sense while calling for self-overcoming.',
    src: ['On the Genealogy of Morality', 'Beyond Good and Evil', 'Thus Spoke Zarathustra', 'Leiter, Nietzsche on Morality (2002)'] },
  { n: 'Charles Sanders Peirce', y: '1839–1914', l: 'Classical Pragmatism', conf: 'medium',
    v: [20, -40, -60, -20, null, null, 40, 40, -40],
    note: 'Founder of pragmatism; truth is what inquiry would agree on in the long run; a realist about generals; held that chance is real in the universe.',
    src: ['"How to Make Our Ideas Clear"', '"The Fixation of Belief"'] },
  { n: 'William James', y: '1842–1910', l: 'Classical Pragmatism', conf: 'high',
    v: [50, -80, 40, 20, -40, -20, 80, 50, 0],
    note: 'Truth is what works; the will to believe; the stream of consciousness; a defender of free will and of religious experience.',
    src: ['Pragmatism', 'The Will to Believe', 'The Varieties of Religious Experience', 'The Principles of Psychology'] },

  // 20th and 21st century: continental
  { n: 'Edmund Husserl', y: '1859–1938', l: 'Phenomenology', conf: 'high',
    v: [10, 70, 30, -40, null, -40, 50, -40, 80],
    note: 'Founder of phenomenology: intentionality, the epoché, essences grasped in intuition, the transcendental ego, and later the lifeworld beneath science.',
    src: ['Logical Investigations', 'Ideas I', 'Cartesian Meditations', 'The Crisis of European Sciences'] },
  { n: 'Martin Heidegger', y: '1889–1976', l: 'Existential Phenomenology', conf: 'medium',
    v: [0, -30, 50, 50, null, 70, 40, 70, 100],
    note: 'The question of Being; Dasein as being-in-the-world; authenticity and being-toward-death; later, a critique of technology as "enframing". His Nazi party membership and the Black Notebooks remain contested.',
    src: ['Being and Time', '"The Question Concerning Technology"', 'Dreyfus, Being-in-the-World (1991)'] },
  { n: 'Jean-Paul Sartre', y: '1905–1980', l: 'Atheist Existentialism', conf: 'high',
    v: [-90, null, 30, 80, null, 0, 100, 90, 70],
    note: 'Existence precedes essence; we are condemned to be free; bad faith; hell is other people. Later tried to join existentialism to Marxism.',
    src: ['Being and Nothingness', 'Existentialism Is a Humanism', 'Critique of Dialectical Reason'] },
  { n: 'Simone de Beauvoir', y: '1908–1986', l: 'Existentialist feminism', conf: 'high',
    v: [-80, null, 40, 40, null, 10, 90, 90, 70],
    note: 'One is not born, but rather becomes, a woman; freedom is situated and requires the freedom of others; an ethics of ambiguity.',
    src: ['The Second Sex', 'The Ethics of Ambiguity'] },
  { n: 'Maurice Merleau-Ponty', y: '1908–1961', l: 'Existential Phenomenology', conf: 'high',
    v: [-40, -50, 40, null, null, 30, 20, 60, 90],
    note: 'Perception is primary; the lived body, not a detached mind, is the subject of experience; freedom is always situated.',
    src: ['Phenomenology of Perception', 'The Visible and the Invisible'] },
  { n: 'Albert Camus', y: '1913–1960', l: 'Absurdism', conf: 'high',
    v: [-80, null, 20, 60, 30, -20, 50, 40, 50],
    note: 'The absurd is the clash between our demand for meaning and a silent universe; answer it with revolt, not suicide or faith; rebellion that sets its own limits.',
    src: ['The Myth of Sisyphus', 'The Rebel'] },
  { n: 'Emmanuel Levinas', y: '1906–1995', l: 'Ethical phenomenology', conf: 'medium',
    v: [50, null, 30, -80, 60, 40, null, 60, 90],
    note: 'Ethics is first philosophy: the face of the other person commands me before any theory; infinite responsibility for the other.',
    src: ['Totality and Infinity', 'Otherwise than Being'] },
  { n: 'Hannah Arendt', y: '1906–1975', l: 'Political phenomenology', conf: 'medium',
    v: [-20, null, 10, -20, null, 30, 80, 60, 70],
    note: 'Action, plurality and natality; the banality of evil; who we are is revealed in speech and action among others.',
    src: ['The Human Condition', 'The Origins of Totalitarianism', 'Eichmann in Jerusalem'] },
  { n: 'Hans-Georg Gadamer', y: '1900–2002', l: 'Hermeneutics', conf: 'high',
    v: [0, -10, 40, 0, null, 80, null, 50, 100],
    note: 'Understanding as fusion of horizons; prejudice and tradition as conditions of understanding; language as the medium of being that can be understood.',
    src: ['Truth and Method'] },
  { n: 'Theodor Adorno', y: '1903–1969', l: 'Critical Theory', conf: 'medium',
    v: [-50, 0, 40, -20, null, -20, null, 60, 80],
    note: 'Enlightenment reason turns into domination; the culture industry; negative dialectics; "wrong life cannot be lived rightly."',
    src: ['Dialectic of Enlightenment (with Horkheimer)', 'Negative Dialectics', 'Minima Moralia'] },
  { n: 'Jürgen Habermas', y: '1929–', l: 'Critical Theory', conf: 'high',
    v: [-50, 20, 20, -40, 40, -80, 20, 50, 10],
    note: 'Communicative rationality; discourse ethics (valid norms are those all affected could agree to in rational discourse); defends the unfinished project of modernity.',
    src: ['The Theory of Communicative Action', 'Moral Consciousness and Communicative Action', 'Between Facts and Norms'] },
  { n: 'Michel Foucault', y: '1926–1984', l: 'Post-structuralism', conf: 'high',
    v: [-70, -20, 90, 70, null, 40, -50, 90, 90],
    note: 'Power produces knowledge and subjects; genealogies of the prison, madness and sexuality; later, ethics as care of the self.',
    src: ['Discipline and Punish', 'The History of Sexuality', 'The Order of Things'] },
  { n: 'Jacques Derrida', y: '1930–2004', l: 'Post-structuralism', conf: 'medium',
    v: [-30, -20, 100, 30, null, 20, null, 90, 100],
    note: 'Deconstruction: meaning is endlessly deferred (différance); Western philosophy privileges presence and speech. Later held that justice itself is undeconstructible and wrote on "religion without religion".',
    src: ['Of Grammatology', 'Writing and Difference', '"Force of Law"'] },
  { n: 'Gilles Deleuze', y: '1925–1995', l: 'Post-structuralism', conf: 'medium',
    v: [-60, -30, 80, 70, null, 50, null, 100, 90],
    note: 'A philosophy of difference and immanence; the subject as an effect of processes; with Guattari, desire as productive and concepts as tools.',
    src: ['Difference and Repetition', 'Anti-Oedipus and A Thousand Plateaus (with Guattari)'] },
  { n: 'Judith Butler', y: '1956–', l: 'Post-structuralist feminism', conf: 'high',
    v: [-70, null, 100, 50, null, 30, null, 90, 90],
    note: 'Gender is performative: produced by repeated acts rather than expressing an inner essence; later work on vulnerability and grievable life.',
    src: ['Gender Trouble', 'Bodies That Matter', 'Precarious Life'] },

  // 20th and 21st century: analytic and other
  { n: 'Gottlob Frege', y: '1848–1925', l: 'Logicism', conf: 'medium',
    v: [null, 90, -90, null, null, null, null, null, -100],
    note: 'Founder of modern logic; sense and reference; numbers as objective, non-mental objects; arithmetic as logic.',
    src: ['Foundations of Arithmetic', '"On Sense and Reference"'] },
  { n: 'Bertrand Russell', y: '1872–1970', l: 'Logical atomism', conf: 'high',
    v: [-80, -20, -60, 50, -60, -50, -30, 40, -100],
    note: 'Logical analysis as philosophy\'s method; theory of descriptions; an atheist and later an emotivist-leaning skeptic about objective values.',
    src: ['The Problems of Philosophy', '"On Denoting"', 'Why I Am Not a Christian'] },
  { n: 'Ludwig Wittgenstein (later)', y: '1889–1951', l: 'Ordinary language philosophy', conf: 'medium',
    v: [10, -20, 40, 30, null, 60, null, 40, 20],
    note: 'Meaning is use within language games embedded in forms of life; philosophical problems dissolve when we see how language actually works. Hostile to theory and to scientism.',
    src: ['Philosophical Investigations', 'On Certainty'] },
  { n: 'Rudolf Carnap', y: '1891–1970', l: 'Logical Positivism', conf: 'high',
    v: [-90, -70, 0, 90, null, null, -40, 40, -100],
    note: 'Metaphysics as meaningless pseudo-statements; logical reconstruction of science; questions of existence relative to linguistic frameworks.',
    src: ['The Logical Structure of the World', '"The Elimination of Metaphysics"', '"Empiricism, Semantics, and Ontology"'] },
  { n: 'Karl Popper', y: '1902–1994', l: 'Critical rationalism', conf: 'high',
    v: [-50, -40, -80, -20, -30, -60, 60, -20, -70],
    note: 'Science advances by bold conjectures and falsification; realism about the world; an "open universe" with genuine indeterminism; the open society against historicism.',
    src: ['The Logic of Scientific Discovery', 'Conjectures and Refutations', 'The Open Society and Its Enemies'] },
  { n: 'W. V. O. Quine', y: '1908–2000', l: 'Analytic Naturalism', conf: 'high',
    v: [-100, -90, -50, 60, null, null, -60, 40, -80],
    note: 'No analytic/synthetic distinction; epistemology naturalized as psychology; to be is to be the value of a bound variable; physicalism.',
    src: ['"Two Dogmas of Empiricism"', 'Word and Object', '"Epistemology Naturalized"'] },
  { n: 'Elizabeth Anscombe', y: '1919–2001', l: 'Neo-Aristotelian Virtue Ethics', conf: 'high',
    v: [100, 20, -80, -90, 80, 40, 60, 0, -40],
    note: 'Modern Moral Philosophy attacked consequentialism and launched virtue ethics; some acts, like killing the innocent, are never permitted; a Catholic convert.',
    src: ['"Modern Moral Philosophy"', 'Intention', '"Mr Truman\'s Degree"'] },
  { n: 'Iris Murdoch', y: '1919–1999', l: 'Moral realism (Platonist)', conf: 'medium',
    v: [10, null, -70, -90, null, 30, 40, 40, -10],
    note: 'Moral life is attention to reality, especially other people; the Good as a Platonic ideal without God; "unselfing" through love and art.',
    src: ['The Sovereignty of Good', 'Metaphysics as a Guide to Morals'] },
  { n: 'Simone Weil', y: '1909–1943', l: 'Christian mysticism', conf: 'medium',
    v: [100, null, -60, -90, 60, -50, null, 60, 60],
    note: 'Attention as the core of moral and spiritual life; affliction; obligations come before rights; "decreation" of the self.',
    src: ['Gravity and Grace', 'The Need for Roots', 'Waiting for God'] },
  { n: 'John Rawls', y: '1921–2002', l: 'Kantian Contractualism', conf: 'high',
    v: [-30, 20, -20, 0, 70, -80, null, 20, -60],
    note: 'Justice as fairness chosen behind a veil of ignorance; equal basic liberties and the difference principle; political liberalism for a pluralist society.',
    src: ['A Theory of Justice', 'Political Liberalism'] },
  { n: 'Robert Nozick', y: '1938–2002', l: 'Libertarian rights theory', conf: 'high',
    v: [-30, 0, -50, -40, 80, -30, 30, 40, -60],
    note: 'Rights as side constraints; the minimal state; the entitlement theory of justice; the experience machine against hedonism; the closest-continuer theory of identity.',
    src: ['Anarchy, State, and Utopia', 'Philosophical Explanations'] },
  { n: 'David Lewis', y: '1941–2001', l: 'Analytic metaphysics', conf: 'high',
    v: [-90, 60, -90, 0, null, null, -50, 60, -90],
    note: 'Modal realism: all possible worlds are as real as ours; Humean supervenience; persons as made of temporal parts; compatibilism.',
    src: ['On the Plurality of Worlds', 'Counterfactuals', '"Survival and Identity"'] },
  { n: 'Derek Parfit', y: '1942–2017', l: 'Non-naturalist realism', conf: 'high',
    v: [-60, 50, -70, -90, -30, -90, -60, 90, -80],
    note: 'Personal identity is not what matters; reductionism about persons; non-natural normative truths; the convergence of Kantian, contractualist and consequentialist ethics.',
    src: ['Reasons and Persons', 'On What Matters'] },
  { n: 'Alasdair MacIntyre', y: '1929–2025', l: 'Neo-Aristotelian Virtue Ethics', conf: 'high',
    v: [80, null, -40, -60, 40, 90, 40, -30, 30],
    note: 'The Enlightenment project failed; ethics makes sense only within traditions, practices and the narrative unity of a life; later a Thomist.',
    src: ['After Virtue', 'Whose Justice? Which Rationality?', 'Dependent Rational Animals'] },
  { n: 'Richard Rorty', y: '1931–2007', l: 'Neopragmatism', conf: 'high',
    v: [-80, -80, 100, 70, -30, 70, -20, 80, 40],
    note: 'The mind is not a mirror of nature; truth is what our peers let us get away with saying; liberal irony and solidarity; reducing cruelty as the political aim.',
    src: ['Philosophy and the Mirror of Nature', 'Contingency, Irony, and Solidarity'] },
  { n: 'Daniel Dennett', y: '1942–2024', l: 'Analytic Naturalism', conf: 'high',
    v: [-100, -60, -50, 30, -30, -30, -40, 70, -70],
    note: 'Consciousness explained functionally; the self as a "center of narrative gravity"; compatibilist free will "worth wanting"; Darwinism as a universal acid.',
    src: ['Consciousness Explained', 'Elbow Room', 'Darwin\'s Dangerous Idea'] },
  { n: 'Thomas Nagel', y: '1937–', l: 'Rationalist realism', conf: 'high',
    v: [30, 60, -60, -70, 0, -60, null, -40, -60],
    note: 'What is it like to be a bat? Subjective experience resists physical reduction; objective moral reasons; Mind and Cosmos doubts materialist neo-Darwinism.',
    src: ['"What Is It Like to Be a Bat?"', 'The View from Nowhere', 'Mind and Cosmos'] },
  { n: 'David Chalmers', y: '1966–', l: 'Naturalistic dualism', conf: 'high',
    v: [20, 70, -60, -20, null, null, null, 30, -80],
    note: 'The hard problem of consciousness; zombies are conceivable, so consciousness is not physical; open to panpsychism; co-author of the PhilPapers Surveys.',
    src: ['The Conscious Mind', 'Reality+'] },
  { n: 'Peter Singer', y: '1946–', l: 'Utilitarianism', conf: 'high',
    v: [-80, -30, -50, -60, -100, -100, -40, 20, -60],
    note: 'Equal consideration of interests regardless of species or distance; famine relief as obligation; effective altruism. Moved from preference utilitarianism to objective hedonism.',
    src: ['"Famine, Affluence, and Morality"', 'Animal Liberation', 'Practical Ethics', 'The Point of View of the Universe (with de Lazari-Radek)'] },
  { n: 'Martha Nussbaum', y: '1947–', l: 'Capabilities approach', conf: 'high',
    v: [-20, null, -50, -60, -20, -40, null, null, -20],
    note: 'An objective list of central human capabilities as the basis of justice; Aristotelian and Stoic influences; emotions as intelligent judgments.',
    src: ['Creating Capabilities', 'The Fragility of Goodness', 'Upheavals of Thought'] },
  { n: 'Alfred North Whitehead', y: '1861–1947', l: 'Process Philosophy', conf: 'medium',
    v: [40, 20, -20, -20, null, -20, 50, 70, 30],
    note: 'Reality as a process of "actual occasions"; God as both primordial and consequent, changing with the world.',
    src: ['Process and Reality', 'Science and the Modern World'] },
  { n: 'John Dewey', y: '1859–1952', l: 'Classical Pragmatism', conf: 'high',
    v: [-60, -70, 40, 20, -50, -30, -20, 60, 20],
    note: 'Ideas as instruments for solving problems; experience and nature continuous; democracy as a way of life; education through experience.',
    src: ['Experience and Nature', 'Democracy and Education', 'Human Nature and Conduct'] },
  { n: 'Ayn Rand', y: '1905–1982', l: 'Objectivism', conf: 'medium',
    v: [-100, 30, -100, -100, 40, 70, 100, -60, -40],
    note: 'Popular rather than academic. Existence exists; reason as the only means of knowledge; rational selfishness as virtue; free will as the choice to think.',
    src: ['The Virtue of Selfishness', 'Introduction to Objectivist Epistemology', 'Atlas Shrugged'] },
  { n: 'Sam Harris', y: '1967–', l: 'Scientific moral realism', conf: 'medium',
    v: [-100, -20, -60, -80, -80, -60, -100, 90, -60],
    note: 'Popular rather than academic. Morality as facts about the well-being of conscious creatures, discoverable by science; free will as an illusion; meditation shows the self is an illusion.',
    src: ['The Moral Landscape', 'Free Will', 'Waking Up'] }
];
