// Schools of thought. Vector order: nat, know, real, moral, ethic, scope, will, self, pmethod.
// null = the school takes no characteristic position on that axis.
// core: the central idea. claims: what it holds. debates: arguments inside it. src: key texts and a standard secondary source.
const SCHOOLS = [
  { name: 'Platonism', v: [80, 90, -80, -90, null, 20, null, -90, -20],
    core: 'Behind the changing world of the senses stand eternal, unchanging Forms (the Good, Justice, Beauty) that reason can grasp. The soul is immortal and knowledge is its recollection of the Forms.',
    claims: ['Universals and abstract objects really exist', 'Knowledge comes through reason, not the senses', 'The Good is objective and can be known', 'The soul is distinct from the body and outlives it'],
    debates: 'How particulars "participate" in Forms (Plato\'s own Parmenides raises the problem); whether mathematical Platonism survives without the ethics.',
    src: 'Plato, Republic, Phaedo, Meno; Annas, An Introduction to Plato\'s Republic (1981)' },
  { name: 'Aristotelianism', v: [10, -20, -80, -70, null, 70, 30, -60, -40],
    core: 'Things have natures, and a good human life (eudaimonia) is the full exercise of our rational nature through virtues of character and intellect, lived in a political community.',
    claims: ['Form exists in things, not apart from them', 'Knowledge starts from perception and rises to first principles', 'Virtue is a mean between extremes, learned by practice', 'Humans are political animals'],
    debates: 'How much of his biology-based ethics survives Darwin; whether his account of the soul is a dualism.',
    src: 'Aristotle, Nicomachean Ethics, Metaphysics, De Anima, Politics; Kraut, Aristotle on the Human Good (1989)' },
  { name: 'Stoicism', v: [30, -10, -70, -80, 40, -60, -30, -20, -20],
    core: 'The cosmos is rational and providential. Virtue is the only good; externals like health and wealth are "indifferent". We control only our judgments, and should live according to nature as citizens of the world.',
    claims: ['Only virtue is good', 'Emotions come from false judgments and can be corrected', 'Everything happens by fate, yet assent is up to us', 'All humans share reason and form one cosmopolis'],
    debates: 'Whether fate leaves room for responsibility (Chrysippus\' compatibilism); modern "practical Stoicism" often drops the cosmology.',
    src: 'Epictetus, Discourses and Handbook; Marcus Aurelius, Meditations; Long & Sedley, The Hellenistic Philosophers (1987)' },
  { name: 'Epicureanism', v: [-80, -70, -70, -30, -50, 40, 30, 30, -30],
    core: 'Everything is atoms and void; the gods do not intervene and death is nothing to us. The good life is tranquil pleasure: freedom from pain and fear, among friends.',
    claims: ['Atomist materialism', 'Pleasure (as absence of pain) is the good', 'Fear of death and the gods is irrational', 'Friendship and withdrawal from politics'],
    debates: 'Whether the atomic "swerve" really secures free will; how hedonism avoids selfishness.',
    src: 'Epicurus, Letter to Menoeceus; Lucretius, De Rerum Natura; Long & Sedley (1987)' },
  { name: 'Pyrrhonian Skepticism', v: [null, -30, 40, 50, null, 40, null, null, 0],
    core: 'For every argument there is an equally strong counter-argument, so suspend judgment; tranquility follows. In practice, follow appearances, custom and law.',
    claims: ['Suspension of judgment on all non-evident matters', 'Tranquility through not believing', 'Living by appearances and custom'],
    debates: 'Whether a consistent skeptic can live or act at all (the apraxia objection).',
    src: 'Sextus Empiricus, Outlines of Pyrrhonism; Annas & Barnes, The Modes of Scepticism (1985)' },
  { name: 'Confucianism', v: [10, null, -40, -60, 30, 90, null, 30, 40],
    core: 'Human goodness is cultivated through ritual, learning and right relationships (parent and child, ruler and subject, friends). Virtue spreads outward from the family to the state.',
    claims: ['Ren (humaneness) and li (ritual propriety)', 'Graded love: special duties to those close to us', 'Moral cultivation through study and practice', 'Government by virtue rather than law'],
    debates: 'Mencius (human nature is good) against Xunzi (it is bad and needs shaping); how hierarchical roles fit equal dignity.',
    src: 'Confucius, Analects; Mencius; Xunzi; Ivanhoe, Confucian Moral Self Cultivation (2000)' },
  { name: 'Daoism', v: [40, -40, 50, 50, null, 30, null, 60, 70],
    core: 'The Dao, the way of things, cannot be captured in words. Wisdom is spontaneity and non-forcing action (wu wei), not rules or rival moral systems.',
    claims: ['Names and distinctions are conventional', 'Effortless action over striving', 'Skepticism about fixed moral codes', 'Harmony with nature'],
    debates: 'Laozi\'s political advice for rulers versus Zhuangzi\'s withdrawal and perspectivism.',
    src: 'Laozi, Daodejing; Zhuangzi; Graham, Disputers of the Tao (1989)' },
  { name: 'Madhyamaka Buddhism', v: [30, null, 70, -30, -20, -60, -20, 100, 40],
    core: 'Nothing has intrinsic nature (svabhava); everything arises in dependence on other things. Seeing this "emptiness", including the emptiness of the self, ends craving and suffering.',
    claims: ['No permanent self (anatman)', 'Dependent origination', 'Two truths: conventional and ultimate', 'Compassion for all sentient beings'],
    debates: 'Whether emptiness is a view at all or the end of views; its relation to Yogacara idealism.',
    src: 'Nagarjuna, Mulamadhyamakakarika; Garfield, The Fundamental Wisdom of the Middle Way (1995); Siderits, Buddhism as Philosophy (2007)' },
  { name: 'Advaita Vedanta', v: [90, 40, 40, -50, 30, -30, 0, -40, 40],
    core: 'Only Brahman, undivided consciousness, is ultimately real. The individual self (Atman) is identical with Brahman; the many-ness of the world is appearance (maya). Liberation is realizing this.',
    claims: ['Non-dualism: Atman is Brahman', 'The world of plurality is appearance', 'Knowledge, not action, brings liberation', 'Scripture and direct insight as sources'],
    debates: 'Ramanuja\'s qualified non-dualism and Madhva\'s dualism reject the identity claim.',
    src: 'Shankara, commentary on the Brahma Sutras; Deutsch, Advaita Vedanta (1969)' },
  { name: 'Thomism', v: [90, 10, -90, -90, 60, 40, 70, -90, -40],
    core: 'Aquinas\'s synthesis of Aristotle and Christianity: God\'s existence can be shown by reason; natural law, knowable by reason, grounds morality; grace perfects nature.',
    claims: ['Five ways to God from the world', 'Natural law and some exceptionless norms', 'The soul as the form of the body', 'Faith and reason cannot conflict'],
    debates: 'Analytical versus traditional Thomists; how "new natural law" theory (Finnis, Grisez) relates to Aquinas.',
    src: 'Aquinas, Summa Theologiae; Kenny, Aquinas (1980); Feser, Aquinas (2009)' },
  { name: 'Islamic Falsafa', v: [80, 70, -80, -70, 40, 0, 0, -80, -50],
    core: 'Greek philosophy developed within Islam: God as the necessary existent, an immaterial intellect, and a demonstrative reason that agrees with revelation properly understood.',
    claims: ['Proof of a Necessary Existent', 'The rational soul is immaterial (Avicenna\'s "floating man")', 'Demonstration as the highest form of knowledge', 'Harmony of religion and philosophy'],
    debates: 'Al-Ghazali\'s attack on the philosophers and Averroes\' reply; the eternity of the world.',
    src: 'Avicenna, The Healing; Averroes, The Decisive Treatise; Adamson, Philosophy in the Islamic World (2016)' },
  { name: 'Cartesian Rationalism', v: [70, 90, -70, -50, null, null, 90, -90, -60],
    core: 'Rebuild knowledge from certainty: I think, therefore I am. Clear and distinct ideas, guaranteed by a non-deceiving God, give knowledge of a world of extended matter and thinking minds.',
    claims: ['Methodical doubt', 'Mind-body dualism', 'Innate ideas', 'Libertarian freedom of the will'],
    debates: 'The interaction problem; the "Cartesian circle"; Spinoza and Leibniz push rationalism in other directions.',
    src: 'Descartes, Meditations on First Philosophy; Cottingham, Descartes (1986)' },
  { name: 'Classical Empiricism', v: [-20, -90, 0, 20, null, null, -30, 30, -50],
    core: 'All ideas come from experience. Locke, Berkeley and Hume follow this to very different ends: a world of material substance, a world of ideas held in minds, or skepticism about causation and the self.',
    claims: ['No innate ideas', 'Knowledge limited by experience', 'Skepticism about causal necessity (Hume)', 'The self as a bundle of perceptions (Hume)'],
    debates: 'Whether empiricism leads inevitably to Hume\'s skepticism, and how to answer it.',
    src: 'Locke, Essay Concerning Human Understanding; Berkeley, Principles; Hume, Treatise of Human Nature' },
  { name: 'Kantianism', v: [30, 60, 40, -80, 90, -90, 70, -30, -30],
    core: 'The mind structures experience through space, time and the categories, so we know appearances, not things in themselves. Morality is the categorical imperative: act only on maxims you could will as universal law, and treat persons as ends.',
    claims: ['Synthetic a priori knowledge', 'Transcendental idealism', 'Duty and the categorical imperative', 'Autonomy and the dignity of rational beings'],
    debates: 'Whether transcendental idealism is needed; Kantian constructivists (Rawls, Korsgaard) versus realists.',
    src: 'Kant, Critique of Pure Reason; Groundwork of the Metaphysics of Morals; Allison, Kant\'s Transcendental Idealism (1983)' },
  { name: 'Hegelian Idealism', v: [50, 70, 50, -40, 20, 60, 30, 30, 70],
    core: 'Reality is Spirit coming to know itself through history. Contradictions drive development; freedom is realized in ethical life (family, civil society, state) and in mutual recognition.',
    claims: ['Dialectical development', 'Absolute idealism', 'Freedom as realized in institutions', 'Selfhood through recognition by others'],
    debates: 'Right Hegelians (religious, state-affirming) versus Left Hegelians (Feuerbach, Marx); metaphysical versus "non-metaphysical" readings.',
    src: 'Hegel, Phenomenology of Spirit; Philosophy of Right; Pinkard, Hegel\'s Phenomenology (1994)' },
  { name: 'Utilitarianism', v: [-50, -40, -60, -50, -100, -90, -30, null, -60],
    core: 'The right act is the one that produces the greatest total well-being, counting everyone equally.',
    claims: ['Consequences alone determine rightness', 'Impartiality: each counts for one', 'Well-being (pleasure, preference or flourishing) is what matters', 'Moral reform of law and institutions'],
    debates: 'Act versus rule versus two-level utilitarianism; hedonism versus preference satisfaction; demandingness.',
    src: 'Bentham, Introduction to the Principles of Morals and Legislation; Mill, Utilitarianism; Sidgwick, The Methods of Ethics' },
  { name: 'Historical Materialism', v: [-90, -50, 10, 40, -40, -40, -60, 60, 50],
    core: 'Material production and class struggle drive history; ideas, law and morality largely reflect economic relations. Philosophy\'s job is to change the world, not only interpret it.',
    claims: ['Materialism about history', 'Ideology critique', 'Alienation under capitalism', 'Human nature as social and historical'],
    debates: 'Whether Marx had an ethics at all; humanist versus structuralist readings (Althusser).',
    src: 'Marx, Economic and Philosophic Manuscripts of 1844; The German Ideology; Cohen, Karl Marx\'s Theory of History (1978)' },
  { name: 'Atheist Existentialism', v: [-60, null, 30, 80, null, 20, 100, 80, 70],
    core: 'There is no God and no given human nature: existence precedes essence. We are radically free and responsible for what we make of ourselves, and must act without guarantees.',
    claims: ['Radical freedom and responsibility', 'No pre-given meaning', 'Bad faith as self-deception about freedom', 'Authenticity as owning one\'s choices'],
    debates: 'How to get an ethics from freedom (Beauvoir\'s attempt); Sartre\'s later turn to Marxism.',
    src: 'Sartre, Being and Nothingness; Existentialism Is a Humanism; Beauvoir, The Ethics of Ambiguity' },
  { name: 'Religious Existentialism', v: [90, -30, 0, -30, null, 60, 90, 20, 80],
    core: 'Truth that matters is subjective in the sense of lived and appropriated. Faith is a passionate commitment beyond reason; the self must become itself before God.',
    claims: ['Truth as subjectivity', 'The leap of faith', 'Anxiety and despair as revealing', 'The single individual over the crowd'],
    debates: 'Kierkegaard\'s irrationalism versus the more rational faith of Marcel, Buber or Tillich.',
    src: 'Kierkegaard, Fear and Trembling; Concluding Unscientific Postscript; Buber, I and Thou' },
  { name: 'Phenomenology', v: [0, 70, 30, -40, null, null, 50, -30, 80],
    core: 'Return "to the things themselves": bracket assumptions about the external world and describe the structures of conscious experience as it is lived, including intentionality, time and embodiment.',
    claims: ['Consciousness is always of something (intentionality)', 'The epoché: bracketing the natural attitude', 'Essences grasped by intuition', 'The lifeworld as the ground of science'],
    debates: 'Husserl\'s transcendental idealism versus the existential turn of Heidegger and Merleau-Ponty.',
    src: 'Husserl, Logical Investigations; Ideas I; The Crisis of European Sciences; Zahavi, Husserl\'s Phenomenology (2003)' },
  { name: 'Existential Phenomenology', v: [-20, -30, 40, 40, null, 50, 40, 70, 90],
    core: 'We are not detached minds observing a world but beings already engaged in it, through bodies, moods, practices and history. Meaning is found in being-in-the-world before any theory.',
    claims: ['Being-in-the-world', 'The lived body as subject (Merleau-Ponty)', 'Primacy of practical engagement over theory', 'Historicity and finitude'],
    debates: 'Heidegger\'s Nazism and how far it touches his philosophy; whether this tradition supports any ethics.',
    src: 'Heidegger, Being and Time; Merleau-Ponty, Phenomenology of Perception; Dreyfus, Being-in-the-World (1991)' },
  { name: 'Hermeneutics', v: [0, -10, 40, 0, null, 80, null, 50, 100],
    core: 'Understanding is always interpretation from within a tradition. Our "prejudices" are not just errors but conditions of understanding; understanding is a fusion of horizons.',
    claims: ['The hermeneutic circle', 'Tradition and authority as sources of understanding', 'Language as the medium of understanding', 'Against method as the route to truth'],
    debates: 'Habermas against Gadamer on whether tradition can be criticized; Ricoeur\'s "hermeneutics of suspicion".',
    src: 'Gadamer, Truth and Method; Ricoeur, Freud and Philosophy' },
  { name: 'Classical Pragmatism', v: [-30, -70, 30, 20, -50, -20, 40, 50, 0],
    core: 'The meaning of an idea lies in its practical consequences; truth is what works in inquiry over the long run. Philosophy should serve intelligent problem-solving and democratic life.',
    claims: ['Pragmatic maxim', 'Fallibilism', 'Truth tied to inquiry and practice', 'Democracy as a way of life (Dewey)'],
    debates: 'Peirce\'s realist pragmatism versus James\'s more subjective version; James\'s "will to believe".',
    src: 'Peirce, "How to Make Our Ideas Clear"; James, Pragmatism; Dewey, Experience and Nature' },
  { name: 'Neopragmatism', v: [-70, -80, 90, 70, -30, 60, -20, 70, 40],
    core: 'Drop the idea of the mind as a mirror of nature. Truth is not correspondence but what our community lets us say; philosophy should help conversation and reduce cruelty, not find foundations.',
    claims: ['Anti-representationalism', 'Truth as justification within a community', 'Liberal irony', 'Solidarity over objectivity'],
    debates: 'Whether it collapses into relativism (Putnam\'s and Habermas\'s objections).',
    src: 'Rorty, Philosophy and the Mirror of Nature; Contingency, Irony, and Solidarity' },
  { name: 'Logical Positivism', v: [-90, -80, 20, 90, null, null, -40, 40, -100],
    core: 'Only statements verifiable by experience or true by logic are meaningful. Metaphysics, theology and ethics, as traditionally done, are nonsense; philosophy is the logical analysis of science.',
    claims: ['Verification principle', 'Analytic/synthetic distinction', 'Emotivism about ethics', 'Unity of science'],
    debates: 'The verification principle seems not verifiable itself; Quine\'s attack on the analytic/synthetic distinction.',
    src: 'Ayer, Language, Truth and Logic; Carnap, The Logical Structure of the World; Vienna Circle manifesto (1929)' },
  { name: 'Analytic Naturalism', v: [-100, -70, -60, 30, -30, -30, -40, 50, -80],
    core: 'Philosophy is continuous with science. There is no first philosophy; minds are physical systems, and our best theories tell us what exists.',
    claims: ['Physicalism', 'Naturalized epistemology', 'Compatibilism about free will', 'Skepticism about a priori metaphysics'],
    debates: 'Whether consciousness and normativity can be naturalized; reductive versus non-reductive physicalism.',
    src: 'Quine, "Two Dogmas of Empiricism" and "Epistemology Naturalized"; Dennett, Consciousness Explained' },
  { name: 'Post-structuralism', v: [-50, -30, 100, 60, null, 40, -20, 90, 100],
    core: 'Meaning is never fully present or fixed; it depends on differences within language and systems of power. Concepts like the subject, truth and normality have histories and can be taken apart.',
    claims: ['Deconstruction of binary oppositions', 'Power produces knowledge and subjects', 'The subject as constituted, not given', 'Genealogy of present institutions'],
    debates: 'Whether it can ground any normative critique (Habermas\'s charge of performative contradiction).',
    src: 'Derrida, Of Grammatology; Foucault, Discipline and Punish; Deleuze, Difference and Repetition' },
  { name: 'Critical Theory', v: [-60, 0, 30, -30, 40, -30, 20, 50, 70],
    core: 'Philosophy must criticize the social forms that dominate people, including instrumental reason itself. Habermas reconstructs this as a theory of undistorted communication.',
    claims: ['Critique of ideology and the culture industry', 'Instrumental reason as domination', 'Discourse ethics (Habermas)', 'Emancipation as philosophy\'s aim'],
    debates: 'Adorno\'s pessimism versus Habermas\'s rationalism; recognition theory (Honneth).',
    src: 'Horkheimer & Adorno, Dialectic of Enlightenment; Habermas, The Theory of Communicative Action' },
  { name: 'Neo-Aristotelian Virtue Ethics', v: [0, null, -60, -70, 30, 80, 30, -40, 0],
    core: 'Revive virtue and human flourishing as the center of ethics, against modern theories of rules and outcomes. Moral judgment is practical wisdom exercised within practices and traditions.',
    claims: ['Virtues as traits needed to flourish', 'Practical wisdom over decision procedures', 'Natural goodness (Foot)', 'Traditions of inquiry (MacIntyre)'],
    debates: 'Whether it gives action guidance; situationist challenges from psychology.',
    src: 'Anscombe, "Modern Moral Philosophy"; MacIntyre, After Virtue; Foot, Natural Goodness; Hursthouse, On Virtue Ethics' },
  { name: 'Kantian Contractualism', v: [-30, 20, -20, 0, 70, -80, null, 20, -60],
    core: 'Principles of justice and morality are those that free and equal persons could agree to, or could not reasonably reject. Fairness is built from an impartial standpoint.',
    claims: ['The original position and veil of ignorance', 'Priority of the right over the good', 'Justification to each person', 'Reasonable pluralism'],
    debates: 'Communitarian critiques of the "unencumbered self"; Rawls versus Nozick on distributive justice.',
    src: 'Rawls, A Theory of Justice; Scanlon, What We Owe to Each Other' },
  { name: 'Care Ethics', v: [-20, -30, 40, -10, 20, 90, null, 70, 50],
    core: 'Morality begins in relationships of care and dependence, not in abstract principles between independent equals. Attentiveness and responsiveness to particular others are central.',
    claims: ['Relational selves', 'Care as a moral and political value', 'Critique of impartialism', 'Attention to vulnerability and dependence'],
    debates: 'Whether care ethics is a distinct theory or a form of virtue ethics; how it scales to justice.',
    src: 'Gilligan, In a Different Voice; Noddings, Caring; Held, The Ethics of Care' },
  { name: 'Objectivism', v: [-100, 30, -100, -100, 40, 70, 100, -60, -40],
    core: 'Ayn Rand\'s system: reality is objective, reason is our only means of knowledge, rational self-interest is the moral purpose of life, and laissez-faire capitalism is the only moral social system.',
    claims: ['Objective reality and reason', 'Ethical egoism', 'Volitional consciousness', 'Rights as conditions of rational life'],
    debates: 'Academic philosophers largely reject its arguments; disputes among followers (ARI versus the Atlas Society).',
    src: 'Rand, Atlas Shrugged; The Virtue of Selfishness; Peikoff, Objectivism (1991)' },
  { name: 'Process Philosophy', v: [40, 20, -20, -20, null, -20, 50, 70, 30],
    core: 'Reality is made of events and processes, not static substances. God is in process with the world, and novelty and creativity are fundamental.',
    claims: ['Becoming over being', 'Panexperientialism', 'A God who changes with the world', 'Creativity as ultimate'],
    debates: 'Its influence is greater in theology than in philosophy departments.',
    src: 'Whitehead, Process and Reality; Bergson, Creative Evolution' },
  { name: 'Nietzschean Perspectivism', v: [-80, -40, 70, 90, null, 70, -40, 70, 70],
    core: 'God is dead, and with him the ground of traditional morality. There are only perspectives; values must be revalued by those strong enough to create them.',
    claims: ['Genealogy of morality', 'Perspectivism', 'Will to power', 'Affirmation of life (eternal recurrence)'],
    debates: 'Whether perspectivism refutes itself; how much of Nietzsche is an ethics of excellence versus nihilism.',
    src: 'Nietzsche, On the Genealogy of Morality; Beyond Good and Evil; Leiter, Nietzsche on Morality (2002)' }
];
